// Mappings of known morphemes for dynamic parsing fallback
const HETERONYMS_MAP = {
  record: [
    { part_of_speech: "n.", translation: "紀錄; 唱片", breakdown: "re-cord", breakdown_meanings: "re:回; 再次|cord:心; 弦", formula: "「再次」「把心意拉成一根弦」以留存 -> 紀錄", teammate_word: "courage", teammate_translation: "勇氣", teammate_root: "cord", teammate_root_meaning: "心" },
    { part_of_speech: "v.", translation: "記錄; 錄音", breakdown: "re-cord", breakdown_meanings: "re:回; 再次|cord:心; 弦", formula: "「再次」「把聲音記在心中」 -> 記錄", teammate_word: "courage", teammate_translation: "勇氣", teammate_root: "cord", teammate_root_meaning: "心" }
  ],
  present: [
    { part_of_speech: "n.", translation: "禮物; 現在", breakdown: "pre-sent", breakdown_meanings: "pre:在前|sent:存在; 感覺", formula: "放「在前」方「存在」的東西 -> 禮物", teammate_word: "represent", teammate_translation: "代表", teammate_root: "sent", teammate_root_meaning: "存在" },
    { part_of_speech: "v.", translation: "呈現; 贈送", breakdown: "pre-sent", breakdown_meanings: "pre:在前|sent:存在; 感覺", formula: "使物體「在前」方「顯現」 -> 呈現", teammate_word: "represent", teammate_translation: "代表", teammate_root: "sent", teammate_root_meaning: "存在" },
    { part_of_speech: "adj.", translation: "出席的; 在場的", breakdown: "pre-sent", breakdown_meanings: "pre:在前|sent:存在; 感覺", formula: "「在」眼前「存在」的 -> 在場的", teammate_word: "represent", teammate_translation: "代表", teammate_root: "sent", teammate_root_meaning: "存在" }
  ],
  object: [
    { part_of_speech: "n.", translation: "物體; 目標", breakdown: "ob-ject", breakdown_meanings: "ob:反對; 朝向|ject:扔; 投", formula: "「扔」「在眼前」的障礙物 -> 物體", teammate_word: "reject", teammate_translation: "拒絕", teammate_root: "ject", teammate_root_meaning: "扔" },
    { part_of_speech: "v.", translation: "反對; 提出異議", breakdown: "ob-ject", breakdown_meanings: "ob:反對; 朝向|ject:扔; 投", formula: "「朝向」對手「扔」去抗議 -> 反對", teammate_word: "reject", teammate_translation: "拒絕", teammate_root: "ject", teammate_root_meaning: "扔" }
  ],
  conduct: [
    { part_of_speech: "n.", translation: "行為; 品行", breakdown: "con-duc-t", breakdown_meanings: "con:共同|duc:引導", formula: "「引導」自己與「他人共同」遵守的規範 -> 品行", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導" },
    { part_of_speech: "v.", translation: "引導; 實施", breakdown: "con-duc-t", breakdown_meanings: "con:共同|duc:引導", formula: "「共同」「引導」團隊前進 -> 實施", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導" }
  ],
  contract: [
    { part_of_speech: "n.", translation: "合約; 契約", breakdown: "con-tract", breakdown_meanings: "con:共同|tract:拉", formula: "把雙方條件「拉」到「一起」 -> 合約", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉" },
    { part_of_speech: "v.", translation: "收縮; 感染; 締結", breakdown: "con-tract", breakdown_meanings: "con:共同|tract:拉", formula: "把物體往「內部拉」緊 -> 收縮", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉" }
  ],
  produce: [
    { part_of_speech: "n.", translation: "農產品", breakdown: "pro-duce", breakdown_meanings: "pro:向前|duce:引導", formula: "「向前」「引導」土壤生長出來的東西 -> 農產品", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導" },
    { part_of_speech: "v.", translation: "生產; 製造", breakdown: "pro-duce", breakdown_meanings: "pro:向前|duce:引導", formula: "「向前」「引導」出新的成品 -> 生產", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導" }
  ],
  permit: [
    { part_of_speech: "n.", translation: "許可證; 執照", breakdown: "per-mit", breakdown_meanings: "per:穿過; 完全|mit:送; 投擲", formula: "「完全」「送」行放行 -> 許可證", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送" },
    { part_of_speech: "v.", translation: "允許; 容許", breakdown: "per-mit", breakdown_meanings: "per:穿過; 完全|mit:送; 投擲", formula: "「完全」讓其「送」出通過 -> 允許", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送" }
  ],
  suspect: [
    { part_of_speech: "n.", translation: "嫌疑犯", breakdown: "sub-spect", breakdown_meanings: "sub:在下面|spect:看", formula: "在底下偷偷「看」瞧他 -> 嫌疑犯", teammate_word: "inspect", teammate_translation: "檢查", teammate_root: "spect", teammate_root_meaning: "看" },
    { part_of_speech: "v.", translation: "懷疑", breakdown: "sub-spect", breakdown_meanings: "sub:在下面|spect:看", formula: "「在下方」暗中「看」著他 -> 懷疑", teammate_word: "inspect", teammate_translation: "檢查", teammate_root: "spect", teammate_root_meaning: "看" }
  ],
  project: [
    { part_of_speech: "n.", translation: "計畫; 專案", breakdown: "pro-ject", breakdown_meanings: "pro:向前|ject:扔", formula: "「向前」「投擲」出的未來藍圖 -> 計畫", teammate_word: "reject", teammate_translation: "拒絕", teammate_root: "ject", teammate_root_meaning: "扔" },
    { part_of_speech: "v.", translation: "投影; 投射", breakdown: "pro-ject", breakdown_meanings: "pro:向前|ject:扔", formula: "「向前」把光影「扔」出去 -> 投影", teammate_word: "reject", teammate_translation: "拒絕", teammate_root: "ject", teammate_root_meaning: "扔" }
  ],
  conflict: [
    { part_of_speech: "n.", translation: "衝突; 爭執", breakdown: "con-flict", breakdown_meanings: "con:共同; 一起|flict:打撃; 碰撞", formula: "「一起」「碰撞」打撃 -> 衝突", teammate_word: "inflict", teammate_translation: "施加; 處罰", teammate_root: "flict", teammate_root_meaning: "打撃" },
    { part_of_speech: "v.", translation: "衝突; 抵觸", breakdown: "con-flict", breakdown_meanings: "con:共同; 一起|flict:打撃; 碰撞", formula: "「一起」「撞擊」而抵觸 -> 衝突", teammate_word: "inflict", teammate_translation: "施加; 處罰", teammate_root: "flict", teammate_root_meaning: "打撃" }
  ],
  attribute: [
    { part_of_speech: "n.", translation: "屬性; 特質", breakdown: "ad-tribute", breakdown_meanings: "ad:朝向|tribute:給予", formula: "「給予」某物「朝向」它的特徵 -> 特質", teammate_word: "contribute", teammate_translation: "貢獻", teammate_root: "tribute", teammate_root_meaning: "給予" },
    { part_of_speech: "v.", translation: "歸因於", breakdown: "ad-tribute", breakdown_meanings: "ad:朝向|tribute:給予", formula: "「朝向」某處「給予」原因 -> 歸因於", teammate_word: "contribute", teammate_translation: "貢獻", teammate_root: "tribute", teammate_root_meaning: "給予" }
  ],
  content: [
    { part_of_speech: "n.", translation: "內容; 目錄", breakdown: "con-ten-t", breakdown_meanings: "con:共同|ten:拉; 握住", formula: "「共同」「握住」裝在裡面的東西 -> 內容", teammate_word: "maintain", teammate_translation: "維持", teammate_root: "ten", teammate_root_meaning: "握住" },
    { part_of_speech: "adj.", translation: "滿意的; 滿足的", breakdown: "con-ten-t", breakdown_meanings: "con:共同|ten:拉; 握住", formula: "慾望「共同」被「拉」平滿足的 -> 滿意的", teammate_word: "maintain", teammate_translation: "維持", teammate_root: "ten", teammate_root_meaning: "握住" },
    { part_of_speech: "v.", translation: "使滿足", breakdown: "con-ten-t", breakdown_meanings: "con:共同|ten:拉; 握住", formula: "「共同」「握住」慾望 -> 使滿足", teammate_word: "maintain", teammate_translation: "維持", teammate_root: "ten", teammate_root_meaning: "握住" }
  ]
};

const KNOWN_PREFIXES = {
  un: "無; 相反; 否定",
  pre: "前; 預先; 在...之前",
  in: "往內; 進入; 否定",
  re: "回; 再; 重新",
  sym: "共同; 相同; 相似",
  syn: "共同; 相同; 相似",
  a: "無; 沒有; 否定",
  co: "共同; 一起; 聯合",
  con: "共同; 一起; 聯合",
  dis: "不; 否定; 分開",
  ex: "往外; 離開; 向上",
  im: "往內; 進入; 否定",
  sub: "在...下方; 次要的",
  pro: "向前; 公開; 提倡",
  de: "向下; 否定; 除去",
  trans: "跨越; 轉移; 透過",
  inter: "在...之間; 相互",
  contra: "相反; 對立; 反對",
  ad: "朝向; 靠近; 加上",
  ab: "偏離; 離開; 否定",
  ob: "反對; 阻擋; 朝向",
  per: "完全; 穿過; 透過"
};

const KNOWN_ROOTS = {
  ced: { meaning: "走; 讓步", category: "時空與狀態", teammate: "precede" },
  cess: { meaning: "走; 讓步", category: "時空與狀態", teammate: "process" },
  popul: { meaning: "人; 大眾", category: "人與社會", teammate: "popular" },
  audi: { meaning: "聽; 聆聽", category: "感知與思考", teammate: "audience" },
  vis: { meaning: "看; 視線", category: "感知與思考", teammate: "visible" },
  vid: { meaning: "看; 視線", category: "感知與思考", teammate: "provide" },
  pathy: { meaning: "感覺; 情感", category: "感知與思考", teammate: "sympathy" },
  spect: { meaning: "看; 觀察", category: "感知與思考", teammate: "inspect" },
  dict: { meaning: "說; 言語", category: "感知與思考", teammate: "predict" },
  scrib: { meaning: "寫; 記錄", category: "感知與思考", teammate: "describe" },
  script: { meaning: "寫; 記錄", category: "感知與思考", teammate: "script" },
  voc: { meaning: "叫; 聲音; 呼喚", category: "感知與思考", teammate: "vocal" },
  vok: { meaning: "叫; 聲音; 呼喚", category: "感知與思考", teammate: "provoke" },
  tract: { meaning: "拉; 抽引", category: "動作與方向", teammate: "attract" },
  port: { meaning: "搬運; 攜帶; 港口", category: "動作與方向", teammate: "import" },
  struct: { meaning: "建造; 構築", category: "時空與狀態", teammate: "structure" },
  vene: { meaning: "來; 走到", category: "動作與方向", teammate: "intervene" },
  vent: { meaning: "來; 走到", category: "動作與方向", teammate: "prevent" },
  hibit: { meaning: "拿; 持有; 呈現", category: "動作與方向", teammate: "exhibit" },
  way: { meaning: "道路; 方向", category: "時空與狀態", teammate: "subway" },
  marine: { meaning: "海洋的; 航海", category: "時空與狀態", teammate: "submarine" },
  capt: { meaning: "抓; 拿; 取得", category: "動作與方向", teammate: "capture" },
  cap: { meaning: "抓; 拿; 取得", category: "動作與方向", teammate: "capable" },
  cip: { meaning: "抓; 拿; 取得", category: "動作與方向", teammate: "anticipate" },
  fact: { meaning: "做; 製造", category: "動作與方向", teammate: "factory" },
  fect: { meaning: "做; 製造", category: "動作與方向", teammate: "affect" },
  fer: { meaning: "帶; 運送", category: "動作與方向", teammate: "transfer" },
  mit: { meaning: "送; 投擲; 傳送", category: "動作與方向", teammate: "admit" },
  mis: { meaning: "送; 投擲; 傳送", category: "動作與方向", teammate: "dismiss" },
  gen: { meaning: "出生; 產生; 種類", category: "人與社會", teammate: "generate" },
  log: { meaning: "說話; 邏輯; 學科", category: "感知與思考", teammate: "logic" },
  pel: { meaning: "推; 驅逐", category: "動作與方向", teammate: "compel" },
  puls: { meaning: "推; 驅逐", category: "動作與方向", teammate: "pulse" },
  pend: { meaning: "掛; 懸掛; 衡量", category: "時空與狀態", teammate: "depend" },
  pens: { meaning: "掛; 衡量; 花費", category: "時空與狀態", teammate: "expense" },
  pos: { meaning: "放; 放置", category: "動作與方向", teammate: "compose" },
  pon: { meaning: "放; 放置", category: "動作與方向", teammate: "postpone" },
  rupt: { meaning: "斷; 破裂", category: "時空與狀態", teammate: "rupture" },
  sent: { meaning: "感覺; 意識", category: "感知與思考", teammate: "sense" },
  sens: { meaning: "感覺; 意識", category: "感知與思考", teammate: "sensitive" },
  tend: { meaning: "伸展; 趨向", category: "時空與狀態", teammate: "tendency" },
  tens: { meaning: "伸展; 緊張", category: "時空與狀態", teammate: "intense" },
  vert: { meaning: "轉; 轉向", category: "動作與方向", teammate: "convert" },
  vers: { meaning: "轉; 轉向", category: "動作與方向", teammate: "reverse" },
  viv: { meaning: "活; 生命", category: "時空與狀態", teammate: "survive" },
  vit: { meaning: "活; 生命", category: "時空與狀態", teammate: "vital" },
  grad: { meaning: "步; 走; 級別", category: "時空與狀態", teammate: "gradual" },
  gress: { meaning: "步; 走; 級別", category: "時空與狀態", teammate: "progress" },
  fine: { meaning: "界限; 結束; 精細", category: "時空與狀態", teammate: "define" },
  claim: { meaning: "喊叫; 聲稱", category: "感知與思考", teammate: "claim" },
  ple: { meaning: "滿; 填滿", category: "時空與狀態", teammate: "complete" },
  plet: { meaning: "滿; 填滿", category: "時空與狀態", teammate: "deplete" },
  cred: { meaning: "相信; 信任", category: "感知與思考", teammate: "credit" },
  duc: { meaning: "引導; 帶領", category: "動作與方向", teammate: "conduct" },
  duct: { meaning: "引導; 帶領", category: "動作與方向", teammate: "product" },
  flex: { meaning: "彎曲", category: "時空與狀態", teammate: "flexible" },
  flect: { meaning: "彎曲", category: "時空與狀態", teammate: "reflect" },
  flu: { meaning: "流; 流動", category: "時空與狀態", teammate: "influence" },
  ject: { meaning: "投; 擲; 丟", category: "動作與方向", teammate: "reject" },
  sol: { meaning: "單獨; 太陽", category: "時空與狀態", teammate: "solitary" },
  spir: { meaning: "呼吸; 渴望", category: "感知與思考", teammate: "inspire" },
  tort: { meaning: "扭曲; 擰", category: "時空與狀態", teammate: "torture" },
  val: { meaning: "價值; 強壯", category: "人與社會", teammate: "value" }
};

const KNOWN_SUFFIXES = {
  ent: "形容詞字尾 (表示狀態/性質)",
  ed: "分詞/形容詞字尾 (表示被動/完成)",
  ous: "形容詞字尾 (表示多...的; 充滿)",
  ar: "形容詞/名詞字尾 (表示...的)",
  ence: "名詞字尾 (表示狀態/性質)",
  ance: "名詞字尾 (表示狀態/性質)",
  ual: "形容詞字尾 (表示...的)",
  y: "名詞/形容詞字尾 (表示性質/狀態)",
  al: "形容詞/名詞字尾 (表示...的)",
  ive: "形容詞/名詞字尾 (表示有...傾向的)",
  tion: "名詞字尾 (表示狀態/動作)",
  sion: "名詞字尾 (表示狀態/動作)",
  able: "形容詞字尾 (表示可...的; 能)",
  ible: "形容詞字尾 (表示可...的; 能)",
  ly: "副詞/形容詞字尾 (表示...地)",
  ment: "名詞字尾 (表示行為/結果)",
  ness: "名詞字尾 (表示性質/狀態)",
  ity: "名詞字尾 (表示狀態/性質)",
  ic: "形容詞/名詞字尾 (表示...的)",
  ist: "名詞字尾 (表示專業人士/信仰者)",
  ism: "名詞字尾 (表示主義/思想/制度)",
  er: "名詞字尾 (表示人/物/主動者)",
  or: "名詞字尾 (表示人/物/主動者)",
  ate: "動詞/形容詞/名詞字尾 (表示做; 具備)",
  ify: "動詞字尾 (表示使...化)",
  ize: "動詞字尾 (表示使...化)",
  ise: "動詞字尾 (表示使...化)"
};

function getMorphemeType(part) {
  const cleanPart = part.toLowerCase().trim();
  if (KNOWN_ROOTS[cleanPart]) return "root";
  if (KNOWN_PREFIXES[cleanPart]) return "prefix";
  if (KNOWN_SUFFIXES[cleanPart]) return "suffix";
  
  // Heuristic fallbacks
  if (cleanPart.length <= 3 && ["ed", "ly", "al", "ar", "er", "or", "ic", "fy", "en", "y"].includes(cleanPart)) {
    return "suffix";
  }
  if (["tion", "sion", "ment", "ness", "able", "ible", "less", "ship", "hood", "ous", "ent", "ant", "ive", "ity", "ise", "ize", "ate", "ify"].some(s => cleanPart.endsWith(s) || cleanPart === s)) {
    return "suffix";
  }
  if (["un", "re", "in", "im", "il", "ir", "dis", "mis", "non", "pre", "post", "anti", "pro", "sub", "super", "trans", "over", "under", "de", "ex", "sym", "syn", "co", "con", "ad", "ab", "ob", "per", "inter", "contra"].some(p => cleanPart.startsWith(p) || cleanPart === p)) {
    return "prefix";
  }
  return "root";
}

// 200 typical High School etymology words classified by level and category
const DEFAULT_WORDS = [
  // 1-20
  { word: "unprecedented", part_of_speech: "adj.", translation: "史無前例的; 空前的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "un-pre-ced-ent-ed", breakdown_meanings: "un:無|pre:前|ced:走|ent:形容詞字尾|ed:分詞字尾", formula: "「無」「前」人「走」過的", teammate_word: "precede", teammate_translation: "在...之前; 先於", teammate_root: "ced", teammate_root_meaning: "走", starred: false },
  { word: "populous", part_of_speech: "adj.", translation: "人口稠密的; 擁擠的", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "popul-ous", breakdown_meanings: "popul:人|ous:多...的", formula: "「人」很多的狀態", teammate_word: "popular", teammate_translation: "流行的; 受歡迎的", teammate_root: "popul", teammate_root_meaning: "人", starred: false },
  { word: "precede", part_of_speech: "v.", translation: "在...之前; 先於", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "pre-ced", breakdown_meanings: "pre:在...之前|ced:走", formula: "「走」在「前方」", teammate_word: "unprecedented", teammate_translation: "史無前例的", teammate_root: "ced", teammate_root_meaning: "走", starred: false },
  { word: "audiovisual", part_of_speech: "adj.", translation: "視聽的; 影音的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "audi-o-vis-ual", breakdown_meanings: "audi:聽|o:連接字母|vis:看|ual:形容詞字尾", formula: "可「聽」又可「看」的", teammate_word: "audience", teammate_translation: "聽眾; 觀眾", teammate_root: "audi", teammate_root_meaning: "聽", starred: false },
  { word: "sympathy", part_of_speech: "n.", translation: "同情心; 共鳴", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "sym-pathy", breakdown_meanings: "sym:共同; 相同|pathy:感情; 感覺", formula: "擁有「相同」的「感受」", teammate_word: "apathy", teammate_translation: "冷漠; 無動於衷", teammate_root: "pathy", teammate_root_meaning: "感覺", starred: false },
  { word: "inspect", part_of_speech: "v.", translation: "檢查; 審查; 視察", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "in-spect", breakdown_meanings: "in:往內; 裡面|spect:看", formula: "往「內部」細細地「看」", teammate_word: "respect", teammate_translation: "尊敬; 尊重", teammate_root: "spect", teammate_root_meaning: "看", starred: false },
  { word: "popular", part_of_speech: "adj.", translation: "流行的; 受歡迎的; 大眾的", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "popul-ar", breakdown_meanings: "popul:人|ar:形容詞字尾", formula: "屬於大部分「人」的", teammate_word: "populous", teammate_translation: "人口稠密的; 擁擠的", teammate_root: "popul", teammate_root_meaning: "人", starred: false },
  { word: "respect", part_of_speech: "v./n.", translation: "尊敬; 尊重; 敬佩", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "re-spect", breakdown_meanings: "re:回頭; 再|spect:看", formula: "讓人想「再」「看」一次的行為", teammate_word: "inspect", teammate_translation: "檢查; 審查", teammate_root: "spect", teammate_root_meaning: "看", starred: false },
  { word: "audience", part_of_speech: "n.", translation: "聽眾; 觀眾; 讀者群", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "audi-ence", breakdown_meanings: "audi:聽|ence:名詞字尾", formula: "前來「聆聽」的人們", teammate_word: "audiovisual", teammate_translation: "視聽的; 影音的", teammate_root: "audi", teammate_root_meaning: "聽", starred: false },
  { word: "apathy", part_of_speech: "n.", translation: "冷漠; 無動於衷", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "a-pathy", breakdown_meanings: "a:無; 沒有|pathy:感覺; 感情", formula: "「沒有」任何的「感覺」", teammate_word: "sympathy", teammate_translation: "同情心; 共鳴", teammate_root: "pathy", teammate_root_meaning: "感覺", starred: false },
  { word: "intervene", part_of_speech: "v.", translation: "干涉; 介入; 調停", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "inter-vene", breakdown_meanings: "inter:在...之間|vene:來", formula: "「走進」兩者「中間」", teammate_word: "prevent", teammate_translation: "預防; 阻止", teammate_root: "vene", teammate_root_meaning: "來", starred: false },
  { word: "contradict", part_of_speech: "v.", translation: "矛盾; 反駁; 頂撞", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "contra-dict", breakdown_meanings: "contra:相反|dict:說", formula: "「說」出「相反」的話", teammate_word: "predict", teammate_translation: "預測; 預言", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "predict", part_of_speech: "v.", translation: "預測; 預言; 預料", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "pre-dict", breakdown_meanings: "pre:預先; 前|dict:說", formula: "在事情發生「前」先「說」", teammate_word: "contradict", teammate_translation: "矛盾; 反駁", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "transport", part_of_speech: "v./n.", translation: "運輸; 運送; 交通工具", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "trans-port", breakdown_meanings: "trans:跨越; 轉移|port:搬運", formula: "「跨越」地區去「搬運」", teammate_word: "import", teammate_translation: "進口; 輸入", teammate_root: "port", teammate_root_meaning: "搬運", starred: false },
  { word: "import", part_of_speech: "v./n.", translation: "進口; 輸入; 引進", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "im-port", breakdown_meanings: "im:往內; 裡面|port:搬運", formula: "把貨物「搬運」進「來」", teammate_word: "export", teammate_translation: "出口; 輸出", teammate_root: "port", teammate_root_meaning: "搬運", starred: false },
  { word: "export", part_of_speech: "v./n.", translation: "出口; 輸出; 傳播", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "ex-port", breakdown_meanings: "ex:往外; 離開|port:搬運", formula: "把貨物「搬運」出「去」", teammate_word: "import", teammate_translation: "進口; 輸入", teammate_root: "port", teammate_root_meaning: "搬運", starred: false },
  { word: "prohibit", part_of_speech: "v.", translation: "禁止; 阻止; 妨礙", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "pro-hibit", breakdown_meanings: "pro:向前; 公開|hibit:拿; 持有", formula: "在他人面前「擋住」不讓「拿」", teammate_word: "exhibit", teammate_translation: "展覽; 展示", teammate_root: "hibit", teammate_root_meaning: "拿; 呈現", starred: false },
  { word: "exhibit", part_of_speech: "v./n.", translation: "展覽; 展示; 展覽品", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "ex-hibit", breakdown_meanings: "ex:往外; 出去|hibit:拿; 呈現", formula: "把物品「拿」出「去」展示", teammate_word: "prohibit", teammate_translation: "禁止; 阻止", teammate_root: "hibit", teammate_root_meaning: "拿; 呈現", starred: false },
  { word: "subway", part_of_speech: "n.", translation: "地鐵; 地下道", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "sub-way", breakdown_meanings: "sub:在...下面|way:道路", formula: "蓋在「地底下」的「道路」", teammate_word: "submarine", teammate_translation: "潛水艇; 海底的", teammate_root: "sub", teammate_root_meaning: "在...下面", starred: false },
  { word: "submarine", part_of_speech: "n./adj.", translation: "潛水艇; 海底的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "sub-marine", breakdown_meanings: "sub:在...下面|marine:海洋的", formula: "「在海洋底下」運行的船隻", teammate_word: "subway", teammate_translation: "地鐵; 地下道", teammate_root: "sub", teammate_root_meaning: "在...下面", starred: false },

  // 21-40
  { word: "attract", part_of_speech: "v.", translation: "吸引; 引起興趣", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "at-tract", breakdown_meanings: "at:朝向|tract:拉", formula: "朝向自己「拉」過來", teammate_word: "distract", teammate_translation: "分心; 分散", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "distract", part_of_speech: "v.", translation: "使分心; 分散注意力", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "dis-tract", breakdown_meanings: "dis:分開|tract:拉", formula: "把注意力「拉」「開」", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "extract", part_of_speech: "v./n.", translation: "拔出; 萃取; 提煉物", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "ex-tract", breakdown_meanings: "ex:往外|tract:拉", formula: "往「外」「拉」出來", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "subtract", part_of_speech: "v.", translation: "減去; 扣除", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "sub-tract", breakdown_meanings: "sub:在下; 減少|tract:拉", formula: "往「下」「拉」走一部分", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "contract", part_of_speech: "n./v.", translation: "合約; 收縮; 感染", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "con-tract", breakdown_meanings: "con:共同; 一起|tract:拉", formula: "把雙方條件「拉」在「起」", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "abstract", part_of_speech: "adj./n.", translation: "抽象的; 摘要", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "abs-tract", breakdown_meanings: "abs:離開|tract:拉", formula: "從具體中「拉」「出」概念", teammate_word: "attract", teammate_translation: "吸引", teammate_root: "tract", teammate_root_meaning: "拉", starred: false },
  { word: "describe", part_of_speech: "v.", translation: "描述; 形容", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "de-scribe", breakdown_meanings: "de:向下; 記錄|scribe:寫", formula: "「寫」「下」詳細的紀錄", teammate_word: "subscribe", teammate_translation: "訂閱", teammate_root: "scribe", teammate_root_meaning: "寫", starred: false },
  { word: "subscribe", part_of_speech: "v.", translation: "訂閱; 捐助; 簽署", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "sub-scribe", breakdown_meanings: "sub:在...下方|scribe:寫", formula: "在名單「下方」「寫」下名字", teammate_word: "describe", teammate_translation: "描述", teammate_root: "scribe", teammate_root_meaning: "寫", starred: false },
  { word: "prescribe", part_of_speech: "v.", translation: "開處方; 規定; 指示", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "pre-scribe", breakdown_meanings: "pre:預先; 在前|scribe:寫", formula: "醫生「預先」「寫」好藥單", teammate_word: "describe", teammate_translation: "描述", teammate_root: "scribe", teammate_root_meaning: "寫", starred: false },
  { word: "manuscript", part_of_speech: "n.", translation: "手稿; 底稿", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "manu-script", breakdown_meanings: "manu:手|script:寫", formula: "用「手」「寫」出來的稿件", teammate_word: "script", teammate_translation: "劇本; 腳本", teammate_root: "script", teammate_root_meaning: "寫", starred: false },
  { word: "script", part_of_speech: "n.", translation: "劇本; 腳本; 字體", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "script", breakdown_meanings: "script:寫", formula: "「寫」出來的台詞腳本", teammate_word: "manuscript", teammate_translation: "手稿", teammate_root: "script", teammate_root_meaning: "寫", starred: false },
  { word: "postscript", part_of_speech: "n.", translation: "附言; 再啟 (P.S.)", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "post-script", breakdown_meanings: "post:在...之後|script:寫", formula: "在信件寫完「之後」再「寫」的附言", teammate_word: "script", teammate_translation: "劇本; 腳本", teammate_root: "script", teammate_root_meaning: "寫", starred: false },
  { word: "structure", part_of_speech: "n./v.", translation: "結構; 構造; 建築物", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "struct-ure", breakdown_meanings: "struct:建造|ure:名詞字尾", formula: "「建造」出來的整體框架", teammate_word: "construct", teammate_translation: "建造; 構築", teammate_root: "struct", teammate_root_meaning: "建造", starred: false },
  { word: "construct", part_of_speech: "v.", translation: "建造; 構築; 創立", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "con-struct", breakdown_meanings: "con:共同; 一起|struct:建造", formula: "把建材「建造」在「一起」", teammate_word: "structure", teammate_translation: "結構", teammate_root: "struct", teammate_root_meaning: "建造", starred: false },
  { word: "instruct", part_of_speech: "v.", translation: "指導; 指示; 命令", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "in-struct", breakdown_meanings: "in:往內; 心智|struct:建造", formula: "在學生心智中「建造」知識", teammate_word: "structure", teammate_translation: "結構", teammate_root: "struct", teammate_root_meaning: "建造", starred: false },
  { word: "destroy", part_of_speech: "v.", translation: "毀壞; 破壞; 毀滅", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "de-stroy", breakdown_meanings: "de:向下; 否定|stroy:建造", formula: "使原本「建造」的東西「倒下」", teammate_word: "structure", teammate_translation: "結構", teammate_root: "struct", teammate_root_meaning: "建造", starred: false },
  { word: "obstruct", part_of_speech: "v.", translation: "阻礙; 妨礙; 堵塞", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "ob-struct", breakdown_meanings: "ob:反對; 阻擋|struct:建造", formula: "在通道上「建造」障礙物「阻擋」", teammate_word: "structure", teammate_translation: "結構", teammate_root: "struct", teammate_root_meaning: "建造", starred: false },
  { word: "visible", part_of_speech: "adj.", translation: "看得見的; 明顯的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "vis-ible", breakdown_meanings: "vis:看|ible:可...的", formula: "可以被「看」見的", teammate_word: "visual", teammate_translation: "視覺的", teammate_root: "vis", teammate_root_meaning: "看", starred: false },
  { word: "visual", part_of_speech: "adj./n.", translation: "視覺的; 視覺效果", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "vis-ual", breakdown_meanings: "vis:看|ual:形容詞字尾", formula: "與「看」相關的", teammate_word: "visible", teammate_translation: "看得見的", teammate_root: "vis", teammate_root_meaning: "看", starred: false },
  { word: "supervise", part_of_speech: "v.", translation: "監督; 管理", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "super-vise", breakdown_meanings: "super:在...之上|vise:看", formula: "站在高處往「下」「看」", teammate_word: "visual", teammate_translation: "視覺的", teammate_root: "vis", teammate_root_meaning: "看", starred: false },

  // 41-60
  { word: "revise", part_of_speech: "v.", translation: "修訂; 修改", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "re-vise", breakdown_meanings: "re:再次; 重新|vise:看", formula: "「重新」「看」一遍以挑錯", teammate_word: "visual", teammate_translation: "視覺的", teammate_root: "vis", teammate_root_meaning: "看", starred: false },
  { word: "provide", part_of_speech: "v.", translation: "提供; 供應", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "pro-vide", breakdown_meanings: "pro:向前; 預先|vide:看", formula: "「預先」「看」到需求並作準備", teammate_word: "provident", teammate_translation: "深謀遠慮的", teammate_root: "vid", teammate_root_meaning: "看", starred: false },
  { word: "provident", part_of_speech: "adj.", translation: "深謀遠慮的; 節儉的", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "pro-vid-ent", breakdown_meanings: "pro:向前; 預先|vid:看|ent:形容詞字尾", formula: "能「預先」「看」到未來的", teammate_word: "provide", teammate_translation: "提供", teammate_root: "vid", teammate_root_meaning: "看", starred: false },
  { word: "dictate", part_of_speech: "v./n.", translation: "口述; 支配; 命令", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "dict-ate", breakdown_meanings: "dict:說|ate:動詞字尾", formula: "「說」出指令讓人寫下", teammate_word: "predict", teammate_translation: "預測", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "indicate", part_of_speech: "v.", translation: "指出; 指明; 暗示", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "in-dicate", breakdown_meanings: "in:往內; 朝向|dicate:說; 宣示", formula: "朝向某物「說」明其位置", teammate_word: "predict", teammate_translation: "預測", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "addict", part_of_speech: "n./v.", translation: "成癮者; 使沉迷", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ad-dict", breakdown_meanings: "ad:朝向; 靠近|dict:說", formula: "嘴裡一直「朝向」某事物「說」要", teammate_word: "predict", teammate_translation: "預測", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "verdict", part_of_speech: "n.", translation: "裁決; 判決", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "ver-dict", breakdown_meanings: "ver:真實|dict:說", formula: "「說」出「真實」的判決", teammate_word: "predict", teammate_translation: "預測", teammate_root: "dict", teammate_root_meaning: "說", starred: false },
  { word: "advocate", part_of_speech: "v./n.", translation: "提倡; 主張; 擁護者", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "ad-voc-ate", breakdown_meanings: "ad:朝向; 靠近|voc:叫; 聲音|ate:動詞字尾", formula: "「朝向」大眾「發聲」支持", teammate_word: "vocal", teammate_translation: "聲音的", teammate_root: "voc", teammate_root_meaning: "聲音", starred: false },
  { word: "vocal", part_of_speech: "adj./n.", translation: "聲音的; 歌唱的; 聲樂", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "voc-al", breakdown_meanings: "voc:聲音; 叫|al:形容詞字尾", formula: "與「聲音」相關的", teammate_word: "advocate", teammate_translation: "提倡", teammate_root: "voc", teammate_root_meaning: "聲音", starred: false },
  { word: "vocation", part_of_speech: "n.", translation: "職業; 使命感", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "voc-ation", breakdown_meanings: "voc:呼喚; 聲音|ation:名詞字尾", formula: "上天對人生的「呼喚」", teammate_word: "vocal", teammate_translation: "聲音的", teammate_root: "voc", teammate_root_meaning: "聲音", starred: false },
  { word: "provoke", part_of_speech: "v.", translation: "激怒; 挑釁; 引起", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "pro-voke", breakdown_meanings: "pro:向前|voke:叫; 呼喊", formula: "「向前」「大叫」挑釁", teammate_word: "revoke", teammate_translation: "撤銷", teammate_root: "vok", teammate_root_meaning: "呼叫", starred: false },
  { word: "revoke", part_of_speech: "v.", translation: "撤銷; 廢除", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "re-voke", breakdown_meanings: "re:往回|voke:叫; 呼喊", formula: "把發出去的指令「叫」「回」", teammate_word: "provoke", teammate_translation: "激怒", teammate_root: "vok", teammate_root_meaning: "呼叫", starred: false },
  { word: "convene", part_of_speech: "v.", translation: "召集; 集合; 開會", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "con-vene", breakdown_meanings: "con:共同; 一起|vene:來", formula: "大家「一起」「來」到某處", teammate_word: "intervene", teammate_translation: "干涉", teammate_root: "vene", teammate_root_meaning: "來", starred: false },
  { word: "prevent", part_of_speech: "v.", translation: "預防; 阻止", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "pre-vent", breakdown_meanings: "pre:預先; 在前|vent:來", formula: "「預先」「來」到前面擋住", teammate_word: "invent", teammate_translation: "發明", teammate_root: "vent", teammate_root_meaning: "來", starred: false },
  { word: "invent", part_of_speech: "v.", translation: "發明; 創造", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "in-vent", breakdown_meanings: "in:往內; 腦中|vent:來", formula: "新點子「來」到「腦中」", teammate_word: "prevent", teammate_translation: "預防", teammate_root: "vent", teammate_root_meaning: "來", starred: false },
  { word: "avenue", part_of_speech: "n.", translation: "大道; 管道", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "a-venue", breakdown_meanings: "a:朝向|venue:來; 到達", formula: "「朝向」某處「來」往的大道", teammate_word: "intervene", teammate_translation: "干涉", teammate_root: "vene", teammate_root_meaning: "來", starred: false },
  { word: "event", part_of_speech: "n.", translation: "事件; 大事; 比賽項目", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "e-vent", breakdown_meanings: "e:往外|vent:來", formula: "事情發展跑「出」「來」的結果", teammate_word: "prevent", teammate_translation: "預防", teammate_root: "vent", teammate_root_meaning: "來", starred: false },
  { word: "capable", part_of_speech: "adj.", translation: "有能力的; 能幹的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "cap-able", breakdown_meanings: "cap:抓; 拿|able:能...的", formula: "「抓」得住事情的", teammate_word: "capture", teammate_translation: "捕捉", teammate_root: "cap", teammate_root_meaning: "抓", starred: false },
  { word: "capture", part_of_speech: "v./n.", translation: "捕捉; 捕獲", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "capt-ure", breakdown_meanings: "capt:抓; 拿|ure:名詞/動詞字尾", formula: "「抓」起來的動作", teammate_word: "capable", teammate_translation: "有能力的", teammate_root: "capt", teammate_root_meaning: "抓", starred: false },
  { word: "accept", part_of_speech: "v.", translation: "接受; 承認", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ac-cept", breakdown_meanings: "ac:朝向|cept:抓; 拿", formula: "「朝向」自己「拿」下來", teammate_word: "except", teammate_translation: "除了...之外", teammate_root: "cept", teammate_root_meaning: "拿", starred: false },

  // 61-80
  { word: "except", part_of_speech: "prep.", translation: "除了...之外", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "ex-cept", breakdown_meanings: "ex:往外|cept:抓; 拿", formula: "往「外」「丟」不「拿」", teammate_word: "accept", teammate_translation: "接受", teammate_root: "cept", teammate_root_meaning: "拿", starred: false },
  { word: "anticipate", part_of_speech: "v.", translation: "預期; 期待", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "anti-cip-ate", breakdown_meanings: "anti:預先; 在前|cip:抓; 拿|ate:動詞字尾", formula: "「預先」「拿」捏未來的狀況", teammate_word: "participate", teammate_translation: "參與", teammate_root: "cip", teammate_root_meaning: "拿", starred: false },
  { word: "participate", part_of_speech: "v.", translation: "參與; 參加", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "parti-cip-ate", breakdown_meanings: "parti:部分|cip:抓; 拿|ate:動詞字尾", formula: "「拿」取其中的一「部分」職責", teammate_word: "anticipate", teammate_translation: "預期", teammate_root: "cip", teammate_root_meaning: "拿", starred: false },
  { word: "factory", part_of_speech: "n.", translation: "工廠; 製造廠", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "fact-ory", breakdown_meanings: "fact:做; 製造|ory:地方", formula: "「製造」東西的「地方」", teammate_word: "affect", teammate_translation: "影響", teammate_root: "fact", teammate_root_meaning: "做", starred: false },
  { word: "affect", part_of_speech: "v.", translation: "影響; 使感動", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "af-fect", breakdown_meanings: "af:朝向|fect:做", formula: "「朝向」某人「做」出改變", teammate_word: "effect", teammate_translation: "效果", teammate_root: "fect", teammate_root_meaning: "做", starred: false },
  { word: "effect", part_of_speech: "n./v.", translation: "效果; 影響", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "ef-fect", breakdown_meanings: "ef:往外; 出來|fect:做", formula: "「做」出「來」的最後結果", teammate_word: "affect", teammate_translation: "影響", teammate_root: "fect", teammate_root_meaning: "做", starred: false },
  { word: "defect", part_of_speech: "n.", translation: "缺點; 缺陷", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "de-fect", breakdown_meanings: "de:向下; 否定|fect:做", formula: "「做」得「不夠」的地方", teammate_word: "affect", teammate_translation: "影響", teammate_root: "fect", teammate_root_meaning: "做", starred: false },
  { word: "efficient", part_of_speech: "adj.", translation: "有效率的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "ef-fici-ent", breakdown_meanings: "ef:往外|fici:做|ent:形容詞字尾", formula: "能大量「做」出「來」成果的", teammate_word: "affect", teammate_translation: "影響", teammate_root: "fect", teammate_root_meaning: "做", starred: false },
  { word: "transfer", part_of_speech: "v./n.", translation: "轉移; 轉車", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "trans-fer", breakdown_meanings: "trans:跨越; 轉移|fer:帶; 運送", formula: "「跨越」地區「帶」過去", teammate_word: "refer", teammate_translation: "參考", teammate_root: "fer", teammate_root_meaning: "帶", starred: false },
  { word: "refer", part_of_speech: "v.", translation: "提及; 參考", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "re-fer", breakdown_meanings: "re:往回|fer:帶", formula: "把問題「帶」「回」源頭參考", teammate_word: "prefer", teammate_translation: "更喜歡", teammate_root: "fer", teammate_root_meaning: "帶", starred: false },
  { word: "prefer", part_of_speech: "v.", translation: "更喜歡", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "pre-fer", breakdown_meanings: "pre:預先; 在前|fer:帶", formula: "把心儀的事物「帶」到最「前面」", teammate_word: "refer", teammate_translation: "參考", teammate_root: "fer", teammate_root_meaning: "帶", starred: false },
  { word: "infer", part_of_speech: "v.", translation: "推論; 推斷", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "in-fer", breakdown_meanings: "in:往內|fer:帶", formula: "從字面「往內」「帶」出深意", teammate_word: "refer", teammate_translation: "參考", teammate_root: "fer", teammate_root_meaning: "帶", starred: false },
  { word: "differ", part_of_speech: "v.", translation: "不同; 相異", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "dif-fer", breakdown_meanings: "dif:分開|fer:帶; 拿", formula: "將看法「分開」「帶」往不同方向", teammate_word: "refer", teammate_translation: "參考", teammate_root: "fer", teammate_root_meaning: "帶", starred: false },
  { word: "admit", part_of_speech: "v.", translation: "承認; 准許進入", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ad-mit", breakdown_meanings: "ad:朝向|mit:送; 放出", formula: "「朝向」內部「放」行", teammate_word: "commit", teammate_translation: "承諾", teammate_root: "mit", teammate_root_meaning: "送", starred: false },
  { word: "commit", part_of_speech: "v.", translation: "承諾; 犯下; 委託", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "com-mit", breakdown_meanings: "com:共同; 一起|mit:送", formula: "把自己的信用「投」「進」去", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送", starred: false },
  { word: "dismiss", part_of_speech: "v.", translation: "解雇; 解散", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "dis-miss", breakdown_meanings: "dis:分開; 離開|miss:送", formula: "「送」人「離開」", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送", starred: false },
  { word: "emit", part_of_speech: "v.", translation: "排放; 散發", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "e-mit", breakdown_meanings: "e:往外|mit:送", formula: "往「外」「送」出氣體或能量", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送", starred: false },
  { word: "transmit", part_of_speech: "v.", translation: "傳送; 傳播; 發射", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "trans-mit", breakdown_meanings: "trans:跨越|mit:送", formula: "「跨越」兩地「送」達", teammate_word: "admit", teammate_translation: "承認", teammate_root: "mit", teammate_root_meaning: "送", starred: false },
  { word: "compel", part_of_speech: "v.", translation: "強迫; 迫使", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "com-pel", breakdown_meanings: "com:共同; 強力|pel:推", formula: "「強力」往一個方向「推」", teammate_word: "expel", teammate_translation: "驅逐", teammate_root: "pel", teammate_root_meaning: "推", starred: false },
  { word: "expel", part_of_speech: "v.", translation: "驅逐; 開除", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "ex-pel", breakdown_meanings: "ex:往外|pel:推", formula: "往「外」「推」出去", teammate_word: "compel", teammate_translation: "強迫", teammate_root: "pel", teammate_root_meaning: "推", starred: false },

  // 81-100
  { word: "impulse", part_of_speech: "n.", translation: "衝動; 刺激", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "im-pulse", breakdown_meanings: "im:往內|pulse:推", formula: "內心被力量「推」動的感覺", teammate_word: "pulse", teammate_translation: "脈搏", teammate_root: "puls", teammate_root_meaning: "推", starred: false },
  { word: "pulse", part_of_speech: "n.", translation: "脈搏; 脈衝", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "pulse", breakdown_meanings: "pulse:推; 搏動", formula: "心臟血液「推」送的跳動", teammate_word: "impulse", teammate_translation: "衝動", teammate_root: "puls", teammate_root_meaning: "推", starred: false },
  { word: "depend", part_of_speech: "v.", translation: "依賴; 取決於", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "de-pend", breakdown_meanings: "de:向下|pend:掛", formula: "「掛」在某個支撐點「下」面", teammate_word: "suspend", teammate_translation: "懸掛", teammate_root: "pend", teammate_root_meaning: "掛", starred: false },
  { word: "suspend", part_of_speech: "v.", translation: "懸掛; 中止; 停職", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "sus-pend", breakdown_meanings: "sus:在...下方|pend:掛", formula: "吊「掛」在半空中", teammate_word: "depend", teammate_translation: "依賴", teammate_root: "pend", teammate_root_meaning: "掛", starred: false },
  { word: "expense", part_of_speech: "n.", translation: "費用; 花費; 支出", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ex-pense", breakdown_meanings: "ex:往外|pense:衡量; 付出", formula: "衡量並「付」出「去」的錢", teammate_word: "expensive", teammate_translation: "昂貴的", teammate_root: "pens", teammate_root_meaning: "花費", starred: false },
  { word: "expensive", part_of_speech: "adj.", translation: "昂貴的; 高價的", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ex-pens-ive", breakdown_meanings: "ex:往外|pens:衡量; 付出|ive:形容詞字尾", formula: "需要大筆「付」出「去」的", teammate_word: "expense", teammate_translation: "費用", teammate_root: "pens", teammate_root_meaning: "花費", starred: false },
  { word: "compensate", part_of_speech: "v.", translation: "補償; 賠償", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "com-pens-ate", breakdown_meanings: "com:共同; 對等|pens:衡量|ate:動詞字尾", formula: "「稱」出對等的金錢以補償", teammate_word: "expense", teammate_translation: "費用", teammate_root: "pens", teammate_root_meaning: "花費", starred: false },
  { word: "compose", part_of_speech: "v.", translation: "組成; 作曲; 寫作", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "com-pose", breakdown_meanings: "com:共同; 一起|pose:放", formula: "將音符或文字「放」在「一起」", teammate_word: "expose", teammate_translation: "暴露", teammate_root: "pos", teammate_root_meaning: "放", starred: false },
  { word: "expose", part_of_speech: "v.", translation: "暴露; 揭露; 曝光", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "ex-pose", breakdown_meanings: "ex:往外|pose:放", formula: "把東西「放」在「外面」給人看", teammate_word: "compose", teammate_translation: "組成", teammate_root: "pos", teammate_root_meaning: "放", starred: false },
  { word: "impose", part_of_speech: "v.", translation: "強加; 課稅", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "im-pose", breakdown_meanings: "im:往內; 在...之上|pose:放", formula: "把責任「放」在他人「身上」", teammate_word: "compose", teammate_translation: "組成", teammate_root: "pos", teammate_root_meaning: "放", starred: false },
  { word: "oppose", part_of_speech: "v.", translation: "反對; 對抗", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "op-pose", breakdown_meanings: "op:相反; 對立|pose:放", formula: "「放」在「相反」的立場", teammate_word: "compose", teammate_translation: "組成", teammate_root: "pos", teammate_root_meaning: "放", starred: false },
  { word: "postpone", part_of_speech: "v.", translation: "延期; 延後", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "post-pone", breakdown_meanings: "post:在...之後|pone:放", formula: "「放」在「後面」做", teammate_word: "component", teammate_translation: "零件; 成分", teammate_root: "pon", teammate_root_meaning: "放", starred: false },
  { word: "component", part_of_speech: "n.", translation: "成分; 零件", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "com-pon-ent", breakdown_meanings: "com:共同|pon:放|ent:名詞字尾", formula: "「放」在「一起」組裝的零件", teammate_word: "postpone", teammate_translation: "延期", teammate_root: "pon", teammate_root_meaning: "放", starred: false },
  { word: "rupture", part_of_speech: "n./v.", translation: "破裂; 裂開", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "rupt-ure", breakdown_meanings: "rupt:斷; 破裂|ure:名詞字尾", formula: "結構「斷」裂的狀態", teammate_word: "interrupt", teammate_translation: "打斷", teammate_root: "rupt", teammate_root_meaning: "斷", starred: false },
  { word: "interrupt", part_of_speech: "v.", translation: "打斷; 中斷", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "inter-rupt", breakdown_meanings: "inter:在...之間|rupt:斷", formula: "在談話「中間」「打斷」", teammate_word: "rupture", teammate_translation: "破裂", teammate_root: "rupt", teammate_root_meaning: "斷", starred: false },
  { word: "bankrupt", part_of_speech: "adj./n./v.", translation: "破產的; 破產者", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "bank-rupt", breakdown_meanings: "bank:銀行; 錢櫃|rupt:斷; 裂", formula: "銀行錢櫃「斷」裂", teammate_word: "rupture", teammate_translation: "破裂", teammate_root: "rupt", teammate_root_meaning: "斷", starred: false },
  { word: "sensitive", part_of_speech: "adj.", translation: "敏感的; 靈敏的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "sens-itive", breakdown_meanings: "sens:感覺; 意識|itive:形容詞字尾", formula: "很有「感覺」的", teammate_word: "sense", teammate_translation: "感官; 意識", teammate_root: "sens", teammate_root_meaning: "感覺", starred: false },
  { word: "sense", part_of_speech: "n./v.", translation: "感官; 意識; 感覺到", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "sense", breakdown_meanings: "sense:感覺", formula: "大腦的「感覺」與意識", teammate_word: "sensitive", teammate_translation: "敏感的", teammate_root: "sens", teammate_root_meaning: "感覺", starred: false },
  { word: "consent", part_of_speech: "v./n.", translation: "同意; 贊成", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "con-sent", breakdown_meanings: "con:共同|sent:感覺; 想法", formula: "擁有「共同」的「想法」", teammate_word: "resent", teammate_translation: "怨恨", teammate_root: "sent", teammate_root_meaning: "感覺", starred: false },
  { word: "resent", part_of_speech: "v.", translation: "怨恨; 憤恨", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "re-sent", breakdown_meanings: "re:反對; 反向|sent:感覺", formula: "產生「反對」的「感覺」", teammate_word: "consent", teammate_translation: "同意", teammate_root: "sent", teammate_root_meaning: "感覺", starred: false },

  // 101-120
  { word: "tendency", part_of_speech: "n.", translation: "趨勢; 傾向", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "tend-ency", breakdown_meanings: "tend:伸展; 趨向|ency:名詞字尾", formula: "朝某個方向「伸展」", teammate_word: "extend", teammate_translation: "延伸", teammate_root: "tend", teammate_root_meaning: "伸展", starred: false },
  { word: "extend", part_of_speech: "v.", translation: "延伸; 擴大; 延長", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "ex-tend", breakdown_meanings: "ex:往外|tend:伸展", formula: "往「外」「伸展」拉長", teammate_word: "tendency", teammate_translation: "趨勢", teammate_root: "tend", teammate_root_meaning: "伸展", starred: false },
  { word: "intense", part_of_speech: "adj.", translation: "強烈的; 劇烈的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "in-tense", breakdown_meanings: "in:往內; 加強|tense:伸展; 拉緊", formula: "精神拉得「極緊」的狀態", teammate_word: "tension", teammate_translation: "緊張; 拉力", teammate_root: "tens", teammate_root_meaning: "拉緊", starred: false },
  { word: "tension", part_of_speech: "n.", translation: "緊張; 拉力; 張力", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "tens-ion", breakdown_meanings: "tens:拉緊|ion:名詞字尾", formula: "拉得「很緊」的物理或心理狀態", teammate_word: "intense", teammate_translation: "強烈的", teammate_root: "tens", teammate_root_meaning: "拉緊", starred: false },
  { word: "convert", part_of_speech: "v.", translation: "轉變; 換算", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "con-vert", breakdown_meanings: "con:共同; 加強|vert:轉", formula: "完全「轉」變原來的狀態", teammate_word: "reverse", teammate_translation: "相反的", teammate_root: "vert", teammate_root_meaning: "轉", starred: false },
  { word: "reverse", part_of_speech: "adj./n./v.", translation: "相反的; 顛倒; 倒車", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "re-verse", breakdown_meanings: "re:往回|verse:轉", formula: "往「回」「轉」", teammate_word: "convert", teammate_translation: "轉變", teammate_root: "verse", teammate_root_meaning: "轉", starred: false },
  { word: "survive", part_of_speech: "v.", translation: "倖存; 活下來", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "sur-vive", breakdown_meanings: "sur:超越; 在...之上|vive:活", formula: "「超越」災難「活」下來", teammate_word: "revive", teammate_translation: "復興; 甦醒", teammate_root: "vive", teammate_root_meaning: "活", starred: false },
  { word: "revive", part_of_speech: "v.", translation: "甦醒; 復興; 重新流行", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "re-vive", breakdown_meanings: "re:再次|vive:活", formula: "「再次」「活」過來", teammate_word: "survive", teammate_translation: "倖存", teammate_root: "vive", teammate_root_meaning: "活", starred: false },
  { word: "vital", part_of_speech: "adj.", translation: "極重要的; 活力充沛的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "vit-al", breakdown_meanings: "vit:活; 生命|al:形容詞字尾", formula: "與「生命」息息相關的", teammate_word: "vivid", teammate_translation: "生動的", teammate_root: "vit", teammate_root_meaning: "生命; 活", starred: false },
  { word: "vivid", part_of_speech: "adj.", translation: "生動的; 鮮艷的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "viv-id", breakdown_meanings: "viv:活; 生命|id:形容詞字尾", formula: "充滿「活」力的", teammate_word: "vital", teammate_translation: "極重要的", teammate_root: "viv", teammate_root_meaning: "生命; 活", starred: false },
  { word: "gradual", part_of_speech: "adj.", translation: "逐漸的; 漸進的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "grad-ual", breakdown_meanings: "grad:步; 階級|ual:形容詞字尾", formula: "一步「一步」前進的", teammate_word: "progress", teammate_translation: "進步", teammate_root: "grad", teammate_root_meaning: "步; 走", starred: false },
  { word: "progress", part_of_speech: "n./v.", translation: "進步; 進展", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "pro-gress", breakdown_meanings: "pro:向前|gress:步; 走", formula: "「向前」「跨步」", teammate_word: "gradual", teammate_translation: "逐漸的", teammate_root: "gress", teammate_root_meaning: "步; 走", starred: false },
  { word: "define", part_of_speech: "v.", translation: "下定義; 限定", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "de-fine", breakdown_meanings: "de:加強|fine:界限; 限制", formula: "劃出確切的「界限」", teammate_word: "infinite", teammate_translation: "無限的", teammate_root: "fine", teammate_root_meaning: "界限", starred: false },
  { word: "infinite", part_of_speech: "adj.", translation: "無限的; 無窮的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "in-fin-ite", breakdown_meanings: "in:無|fin:界限|ite:形容詞字尾", formula: "「沒有」「界限」的", teammate_word: "define", teammate_translation: "下定義", teammate_root: "fin", teammate_root_meaning: "界限", starred: false },
  { word: "confine", part_of_speech: "v.", translation: "限制; 監禁", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "con-fine", breakdown_meanings: "con:共同; 一起|fine:限制; 界限", formula: "關在共同的「界限」內", teammate_word: "define", teammate_translation: "下定義", teammate_root: "fine", teammate_root_meaning: "界限", starred: false },
  { word: "exclaim", part_of_speech: "v.", translation: "呼喊; 驚叫", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "ex-claim", breakdown_meanings: "ex:往外|claim:喊", formula: "大聲「喊」出「去」", teammate_word: "proclaim", teammate_translation: "宣告", teammate_root: "claim", teammate_root_meaning: "喊叫", starred: false },
  { word: "proclaim", part_of_speech: "v.", translation: "宣告; 聲明", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "pro-claim", breakdown_meanings: "pro:向前; 公開|claim:喊", formula: "公開大聲「喊」出來", teammate_word: "exclaim", teammate_translation: "呼喊", teammate_root: "claim", teammate_root_meaning: "喊叫", starred: false },
  { word: "acclaim", part_of_speech: "v./n.", translation: "稱讚; 喝采", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "ac-claim", breakdown_meanings: "ac:朝向|claim:喊", formula: "朝向某人「大聲歡呼」", teammate_word: "exclaim", teammate_translation: "呼喊", teammate_root: "claim", teammate_root_meaning: "喊叫", starred: false },
  { word: "complete", part_of_speech: "adj./v.", translation: "完成; 完整的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "com-plete", breakdown_meanings: "com:完全|plete:滿", formula: "全部填「滿」了", teammate_word: "deplete", teammate_translation: "耗盡", teammate_root: "plet", teammate_root_meaning: "滿", starred: false },
  { word: "deplete", part_of_speech: "v.", translation: "耗盡; 消耗", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "de-plete", breakdown_meanings: "de:向下; 倒空|plete:滿", formula: "使「滿」的東西倒空", teammate_word: "complete", teammate_translation: "完成", teammate_root: "plet", teammate_root_meaning: "滿", starred: false },

  // 121-140
  { word: "implement", part_of_speech: "v./n.", translation: "實施; 工具", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "im-ple-ment", breakdown_meanings: "im:往內|ple:滿|ment:名詞/動詞字尾", formula: "填「滿」需求的工具", teammate_word: "complete", teammate_translation: "完成", teammate_root: "ple", teammate_root_meaning: "滿", starred: false },
  { word: "pedestrian", part_of_speech: "n./adj.", translation: "行人; 徒步的", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "ped-estri-an", breakdown_meanings: "ped:腳|estri:走|an:人", formula: "用「腳」走路的人", teammate_word: "pedal", teammate_translation: "踏板", teammate_root: "ped", teammate_root_meaning: "腳", starred: false },
  { word: "pedal", part_of_speech: "n./v.", translation: "踏板; 踩踏板", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "ped-al", breakdown_meanings: "ped:腳|al:名詞/動詞字尾", formula: "用「腳」控制的踏板", teammate_word: "pedestrian", teammate_translation: "行人", teammate_root: "ped", teammate_root_meaning: "腳", starred: false },
  { word: "monopoly", part_of_speech: "n.", translation: "壟斷; 專賣", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "mono-poly", breakdown_meanings: "mono:單一|poly:賣", formula: "只有一家在「賣」", teammate_word: "monologue", teammate_translation: "獨白", teammate_root: "mono", teammate_root_meaning: "單一", starred: false },
  { word: "monologue", part_of_speech: "n.", translation: "獨白", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "mono-logue", breakdown_meanings: "mono:單一|logue:說話", formula: "「單獨」一個人「說話」", teammate_word: "monopoly", teammate_translation: "壟斷", teammate_root: "mono", teammate_root_meaning: "單一", starred: false },
  { word: "uniform", part_of_speech: "n./adj.", translation: "制服; 一致的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "uni-form", breakdown_meanings: "uni:單一|form:形式; 形狀", formula: "「單一」的「形式」", teammate_word: "universe", teammate_translation: "宇宙", teammate_root: "uni", teammate_root_meaning: "單一", starred: false },
  { word: "universe", part_of_speech: "n.", translation: "宇宙; 全世界", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "uni-verse", breakdown_meanings: "uni:單一|verse:轉", formula: "萬物「轉」為一體", teammate_word: "uniform", teammate_translation: "制服", teammate_root: "uni", teammate_root_meaning: "單一", starred: false },
  { word: "obvious", part_of_speech: "adj.", translation: "明顯的; 顯然的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "ob-vi-ous", breakdown_meanings: "ob:朝向; 面對|vi:路|ous:形容詞字尾", formula: "大「路」正對著眼睛 (很顯眼)", teammate_word: "convey", teammate_translation: "傳達", teammate_root: "via", teammate_root_meaning: "路", starred: false },
  { word: "convey", part_of_speech: "v.", translation: "傳達; 運送", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "con-vey", breakdown_meanings: "con:共同|vey:路; 運送", formula: "引領走上共同的「道路」", teammate_word: "obvious", teammate_translation: "明顯的", teammate_root: "via", teammate_root_meaning: "路", starred: false },
  { word: "deviate", part_of_speech: "v.", translation: "偏離; 越軌", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "de-vi-ate", breakdown_meanings: "de:偏離|vi:路|ate:動詞字尾", formula: "「偏離」正常的「道路」", teammate_word: "obvious", teammate_translation: "明顯的", teammate_root: "via", teammate_root_meaning: "路", starred: false },
  { word: "ascend", part_of_speech: "v.", translation: "上升; 攀登", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "a-scend", breakdown_meanings: "a:朝向|scend:爬; 攀", formula: "朝著上方「爬」", teammate_word: "descend", teammate_translation: "下降", teammate_root: "scend", teammate_root_meaning: "爬", starred: false },
  { word: "descend", part_of_speech: "v.", translation: "下降; 降落; 遺傳", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "de-scend", breakdown_meanings: "de:向下|scend:爬", formula: "往「下」「爬」", teammate_word: "ascend", teammate_translation: "上升", teammate_root: "scend", teammate_root_meaning: "爬", starred: false },
  { word: "transcend", part_of_speech: "v.", translation: "超越; 超出", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "trans-scend", breakdown_meanings: "trans:跨越|scend:爬", formula: "「跨越」障礙「爬」過去", teammate_word: "ascend", teammate_translation: "上升", teammate_root: "scend", teammate_root_meaning: "爬", starred: false },
  { word: "depress", part_of_speech: "v.", translation: "使沮喪; 壓抑; 蕭條", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "de-press", breakdown_meanings: "de:向下|press:壓", formula: "心智被往「下」「壓」", teammate_word: "express", teammate_translation: "表達", teammate_root: "press", teammate_root_meaning: "壓", starred: false },
  { word: "express", part_of_speech: "v./adj./n.", translation: "表達; 特快車; 明確的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "ex-press", breakdown_meanings: "ex:往外|press:壓", formula: "把心裡話「壓」出「去」", teammate_word: "depress", teammate_translation: "使沮喪", teammate_root: "press", teammate_root_meaning: "壓", starred: false },
  { word: "impress", part_of_speech: "v.", translation: "給...留下深刻印象; 印記", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "im-press", breakdown_meanings: "im:往內|press:壓", formula: "在腦海中往「內」「壓」下印記", teammate_word: "express", teammate_translation: "表達", teammate_root: "press", teammate_root_meaning: "壓", starred: false },
  { word: "oppress", part_of_speech: "v.", translation: "壓迫; 欺壓", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "op-press", breakdown_meanings: "op:反對; 對抗|press:壓", formula: "站在對立面「壓」制他人", teammate_word: "express", teammate_translation: "表達", teammate_root: "press", teammate_root_meaning: "壓", starred: false },
  { word: "current", part_of_speech: "n./adj.", translation: "潮流; 水流; 現時的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "cur-rent", breakdown_meanings: "cur:跑|rent:形容詞/名詞字尾 (表示流動)", formula: "一直在「跑」動的事物", teammate_word: "occur", teammate_translation: "發生", teammate_root: "cur", teammate_root_meaning: "跑", starred: false },
  { word: "occur", part_of_speech: "v.", translation: "發生; 出現", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "oc-cur", breakdown_meanings: "oc:朝向|cur:跑", formula: "朝向眼前「跑」出來", teammate_word: "current", teammate_translation: "現時的", teammate_root: "cur", teammate_root_meaning: "跑", starred: false },
  { word: "excursion", part_of_speech: "n.", translation: "遠足; 短途旅行", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "ex-curs-ion", breakdown_meanings: "ex:往外|curs:跑|ion:名詞字尾", formula: "往「外」面「跑」一趟", teammate_word: "occur", teammate_translation: "發生", teammate_root: "cur", teammate_root_meaning: "跑", starred: false },

  // 141-160
  { word: "concur", part_of_speech: "v.", translation: "同意; 一致; 同時發生", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "con-cur", breakdown_meanings: "con:共同|cur:跑", formula: "想法跑到「一起」了", teammate_word: "occur", teammate_translation: "發生", teammate_root: "cur", teammate_root_meaning: "跑", starred: false },
  { word: "pedestal", part_of_speech: "n.", translation: "基座; 底座", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "ped-estal", breakdown_meanings: "ped:腳; 底部|estal:站立", formula: "「腳」站立的「底座」", teammate_word: "pedestrian", teammate_translation: "行人", teammate_root: "ped", teammate_root_meaning: "腳", starred: false },
  { word: "tripod", part_of_speech: "n.", translation: "三腳架", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "tri-pod", breakdown_meanings: "tri:三|pod:腳", formula: "有「三」隻「腳」的架子", teammate_word: "pedal", teammate_translation: "踏板", teammate_root: "ped", teammate_root_meaning: "腳", starred: false },
  { word: "minor", part_of_speech: "adj./n./v.", translation: "次要的; 未成年人; 副修", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "min-or", breakdown_meanings: "min:小|or:形容詞/名詞字尾", formula: "較「小」的", teammate_word: "minimize", teammate_translation: "最小化", teammate_root: "min", teammate_root_meaning: "小", starred: false },
  { word: "minimize", part_of_speech: "v.", translation: "最小化; 輕視", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "min-imize", breakdown_meanings: "min:小|imize:使...化", formula: "使變到最「小」", teammate_word: "minor", teammate_translation: "次要的", teammate_root: "min", teammate_root_meaning: "小", starred: false },
  { word: "minute", part_of_speech: "n./adj.", translation: "分鐘; 微小的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "min-ute", breakdown_meanings: "min:小|ute:名詞/形容詞字尾", formula: "時間或體積被切分到很「小」", teammate_word: "minor", teammate_translation: "次要的", teammate_root: "min", teammate_root_meaning: "小", starred: false },
  { word: "minimum", part_of_speech: "n./adj.", translation: "最小限度; 最低的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "min-imum", breakdown_meanings: "min:小|imum:最...的 (最高級)", formula: "最「小」的值", teammate_word: "minor", teammate_translation: "次要 of", teammate_root: "min", teammate_root_meaning: "小", starred: false },
  { word: "unite", part_of_speech: "v.", translation: "團結; 聯合", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "uni-te", breakdown_meanings: "uni:單一|te:動詞字尾", formula: "結合成「單一」的整體", teammate_word: "unique", teammate_translation: "獨特的", teammate_root: "uni", teammate_root_meaning: "單一", starred: false },
  { word: "unique", part_of_speech: "adj.", translation: "獨特的; 獨一無二的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "uni-que", breakdown_meanings: "uni:單一|que:形容詞字尾", formula: "僅有「單一」的", teammate_word: "unite", teammate_translation: "團結", teammate_root: "uni", teammate_root_meaning: "單一", starred: false },
  { word: "monotone", part_of_speech: "n./adj.", translation: "單調; 單調的", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "mono-tone", breakdown_meanings: "mono:單一|tone:音調", formula: "只有「單一」的「音調」", teammate_word: "monologue", teammate_translation: "獨白", teammate_root: "mono", teammate_root_meaning: "單一", starred: false },
  { word: "polyester", part_of_speech: "n.", translation: "聚酯纖維", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "poly-ester", breakdown_meanings: "poly:多|ester:酯", formula: "「多」個酯分子聚合而成", teammate_word: "polygon", teammate_translation: "多邊形", teammate_root: "poly", teammate_root_meaning: "多", starred: false },
  { word: "multiple", part_of_speech: "adj./n.", translation: "多個的; 倍數", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "multi-ple", breakdown_meanings: "multi:多|ple:折疊; 滿", formula: "包含「多」層折疊的", teammate_word: "multiply", teammate_translation: "乘; 增加", teammate_root: "multi", teammate_root_meaning: "多", starred: false },
  { word: "multiply", part_of_speech: "v.", translation: "乘; 增加; 繁殖", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "multi-ply", breakdown_meanings: "multi:多|ply:折疊; 重複", formula: "使數量「多」倍重複", teammate_word: "multiple", teammate_translation: "多個的", teammate_root: "multi", teammate_root_meaning: "多", starred: false },
  { word: "multitask", part_of_speech: "v./n.", translation: "同時做多件事; 多任務", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "multi-task", breakdown_meanings: "multi:多|task:任務", formula: "同時處理「多」個「任務」", teammate_word: "multiple", teammate_translation: "多個的", teammate_root: "multi", teammate_root_meaning: "多", starred: false },
  { word: "microscope", part_of_speech: "n.", translation: "顯微鏡", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "micro-scope", breakdown_meanings: "micro:微小|scope:看; 鏡", formula: "用來「看」「微小」事物的鏡子", teammate_word: "microwave", teammate_translation: "微波", teammate_root: "micro", teammate_root_meaning: "微小", starred: false },
  { word: "microwave", part_of_speech: "n./v.", translation: "微波; 用微波爐加熱", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "micro-wave", breakdown_meanings: "micro:微小|wave:波動", formula: "頻率極高的「微小」「電波」", teammate_word: "microscope", teammate_translation: "顯微鏡", teammate_root: "micro", teammate_root_meaning: "微小", starred: false },
  { word: "microbe", part_of_speech: "n.", translation: "微生物; 病菌", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "micro-be", breakdown_meanings: "micro:微小|be:生命 (生物)", formula: "極為「微小」的「生命」體", teammate_word: "microscope", teammate_translation: "顯微鏡", teammate_root: "micro", teammate_root_meaning: "微小", starred: false },
  { word: "macroeconomics", part_of_speech: "n.", translation: "總體經濟學", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "macro-economics", breakdown_meanings: "macro:宏大|economics:經濟學", formula: "研究「大」範圍國家經濟的學問", teammate_word: "microscope", teammate_translation: "顯微鏡", teammate_root: "micro", teammate_root_meaning: "微小", starred: false },
  { word: "amateur", part_of_speech: "n./adj.", translation: "業餘愛好者; 業餘的", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "amat-eur", breakdown_meanings: "amat:愛|eur:人 (字尾)", formula: "因為「喜愛」而去做的「人」", teammate_word: "amiable", teammate_translation: "和藹可親的", teammate_root: "am", teammate_root_meaning: "愛", starred: false },
  { word: "amiable", part_of_speech: "adj.", translation: "和藹可親的; 親切的", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "ami-able", breakdown_meanings: "ami:愛; 朋友|able:能...的", formula: "容易讓人「喜愛」的", teammate_word: "amateur", teammate_translation: "業餘愛好者", teammate_root: "am", teammate_root_meaning: "愛", starred: false },

  // 161-180
  { word: "rebel", part_of_speech: "n./v.", translation: "反叛者; 反叛; 造反", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "re-bel", breakdown_meanings: "re:反對|bel:戰爭; 打鬥", formula: "起兵「反對」並進行「打鬥」", teammate_word: "belligerent", teammate_translation: "好戰的", teammate_root: "bel", teammate_root_meaning: "打鬥", starred: false },
  { word: "belligerent", part_of_speech: "adj.", translation: "好戰的; 挑釁的", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "bell-i-ger-ent", breakdown_meanings: "bell:戰爭|ger:攜帶; 進行|ent:形容詞字尾", formula: "「攜帶」「戰爭」傾向的", teammate_word: "rebel", teammate_translation: "反叛者", teammate_root: "bel", teammate_root_meaning: "打鬥", starred: false },
  { word: "brief", part_of_speech: "adj./n./v.", translation: "短暫的; 簡報; 摘要", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "brief", breakdown_meanings: "brief:短", formula: "時間或字句「短」暫的", teammate_word: "brevity", teammate_translation: "簡潔", teammate_root: "brev", teammate_root_meaning: "短", starred: false },
  { word: "abbreviate", part_of_speech: "v.", translation: "縮寫; 簡化", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "ab-brev-iate", breakdown_meanings: "ab:加強|brev:短|iate:動詞字尾", formula: "使字詞變得更「短」", teammate_word: "brief", teammate_translation: "簡短的", teammate_root: "brev", teammate_root_meaning: "短", starred: false },
  { word: "brevity", part_of_speech: "n.", translation: "簡潔; 簡短", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "brev-ity", breakdown_meanings: "brev:短|ity:名詞字尾", formula: "言行「簡短」的性質", teammate_word: "brief", teammate_translation: "簡短的", teammate_root: "brev", teammate_root_meaning: "短", starred: false },
  { word: "carnival", part_of_speech: "n.", translation: "嘉年華; 狂歡節", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "carni-val", breakdown_meanings: "carni:肉; 身體|val:告別 (節日)", formula: "大齋期前「告別吃肉」的狂歡「節慶」", teammate_word: "carnivore", teammate_translation: "食肉動物", teammate_root: "carni", teammate_root_meaning: "肉", starred: false },
  { word: "carnivore", part_of_speech: "n.", translation: "食肉動物", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "carni-vore", breakdown_meanings: "carni:肉|vore:吃", formula: "以「吃」「肉」為生的動物", teammate_word: "carnival", teammate_translation: "嘉年華", teammate_root: "carni", teammate_root_meaning: "肉", starred: false },
  { word: "chronic", part_of_speech: "adj.", translation: "慢性的; 長期的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "chron-ic", breakdown_meanings: "chron:時間|ic:形容詞字尾", formula: "跟隨「時間」長期存在的 (病症)", teammate_word: "chronological", teammate_translation: "按時間順序的", teammate_root: "chron", teammate_root_meaning: "時間", starred: false },
  { word: "chronological", part_of_speech: "adj.", translation: "按時間先後順序的", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "chrono-log-ical", breakdown_meanings: "chrono:時間|log:說話; 邏輯|ical:形容詞字尾", formula: "依據「時間」先後「邏輯」排列的", teammate_word: "chronic", teammate_translation: "慢性的", teammate_root: "chron", teammate_root_meaning: "時間", starred: false },
  { word: "corporation", part_of_speech: "n.", translation: "大公司; 法人團體", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "corpor-ation", breakdown_meanings: "corpor:身體; 團體|ation:名詞字尾", formula: "眾人結合成的一個「法人實體」", teammate_word: "corpse", teammate_translation: "屍體", teammate_root: "corp", teammate_root_meaning: "身體", starred: false },
  { word: "corps", part_of_speech: "n.", translation: "軍團; 兵團; 專業團體", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "corps", breakdown_meanings: "corps:身體; 團體", formula: "緊密相連的「團體」", teammate_word: "corpse", teammate_translation: "屍體", teammate_root: "corp", teammate_root_meaning: "身體", starred: false },
  { word: "corpse", part_of_speech: "n.", translation: "(人的)屍體; 殘骸", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "corpse", breakdown_meanings: "corpse:身體; 屍體", formula: "沒有生命力的「肉體」", teammate_word: "corporation", teammate_translation: "大公司", teammate_root: "corp", teammate_root_meaning: "身體", starred: false },
  { word: "credit", part_of_speech: "n./v.", translation: "信用; 貸款; 讚揚; 歸功於", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "cred-it", breakdown_meanings: "cred:相信|it:行爲 (字尾)", formula: "讓人願意「相信」的資本", teammate_word: "credible", teammate_translation: "可信的", teammate_root: "cred", teammate_root_meaning: "相信", starred: false },
  { word: "credible", part_of_speech: "adj.", translation: "可信的; 可靠的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "cred-ible", breakdown_meanings: "cred:相信|ible:能...的", formula: "「能夠」讓人「相信」的", teammate_word: "credit", teammate_translation: "信用", teammate_root: "cred", teammate_root_meaning: "相信", starred: false },
  { word: "incredible", part_of_speech: "adj.", translation: "難以置信的; 極好的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "in-cred-ible", breakdown_meanings: "in:不|cred:相信|ible:能...的", formula: "「不能」讓人「相信」的 (太誇張的)", teammate_word: "credit", teammate_translation: "信用", teammate_root: "cred", teammate_root_meaning: "相信", starred: false },
  { word: "creed", part_of_speech: "n.", translation: "信條; 核心信仰", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "creed", breakdown_meanings: "creed:相信; 信仰", formula: "心中誓死「相信」的準則", teammate_word: "credit", teammate_translation: "信用", teammate_root: "cred", teammate_root_meaning: "相信", starred: false },
  { word: "democracy", part_of_speech: "n.", translation: "民主制度; 民主國家", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "dem-o-cracy", breakdown_meanings: "dem:人民|cracy:統治", formula: "由「人民」共同「統治」", teammate_word: "demographics", teammate_translation: "人口統計資料", teammate_root: "dem", teammate_root_meaning: "人民", starred: false },
  { word: "demographics", part_of_speech: "n.", translation: "人口統計資料; 人口結構", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "dem-o-graph-ics", breakdown_meanings: "dem:人民|graph:寫; 畫|ics:學問", formula: "「記錄」「人民」分布狀況的學科", teammate_word: "democracy", teammate_translation: "民主", teammate_root: "dem", teammate_root_meaning: "人民", starred: false },
  { word: "domestic", part_of_speech: "adj./n.", translation: "家庭的; 國內的; 家僕", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "dom-estic", breakdown_meanings: "dom:屋; 家|estic:與...相關", formula: "與「家(或國家)」內部相關的", teammate_word: "dominate", teammate_translation: "支配; 主導", teammate_root: "dom", teammate_root_meaning: "屋", starred: false },
  { word: "dominate", part_of_speech: "v.", translation: "支配; 主導; 佔優勢", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "domin-ate", breakdown_meanings: "domin:主人; 屋主|ate:動詞字尾", formula: "像「主人」一樣主導一切", teammate_word: "domestic", teammate_translation: "家庭的", teammate_root: "dom", teammate_root_meaning: "屋", starred: false },

  // 181-200
  { word: "introduce", part_of_speech: "v.", translation: "介紹; 引進; 傳入", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "intro-duce", breakdown_meanings: "intro:往內|duce:引導", formula: "把人或觀念「引導」進「來」", teammate_word: "reduce", teammate_translation: "減少", teammate_root: "duc", teammate_root_meaning: "引導", starred: false },
  { word: "reduce", part_of_speech: "v.", translation: "減少; 降低; 簡化", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "re-duce", breakdown_meanings: "re:往回|duce:引導", formula: "將高度或數量「引導」往「回」降", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導", starred: false },
  { word: "produce", part_of_speech: "v./n.", translation: "生產; 製造; 農產品", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "pro-duce", breakdown_meanings: "pro:向前|duce:引導", formula: "「引導」生長物「向」前出來", teammate_word: "introduce", teammate_translation: "介紹", teammate_root: "duc", teammate_root_meaning: "引導", starred: false },
  { word: "equal", part_of_speech: "adj./v./n.", translation: "相等的; 平等的; 等於; 對手", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "equ-al", breakdown_meanings: "equ:相等|al:形容詞字尾", formula: "「相等」的狀態", teammate_word: "equator", teammate_translation: "赤道", teammate_root: "equ", teammate_root_meaning: "相等", starred: false },
  { word: "equator", part_of_speech: "n.", translation: "赤道", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "equ-ator", breakdown_meanings: "equ:相等|ator:名詞字尾 (表示物)", formula: "將地球平分為「相等」兩半的緯線", teammate_word: "equal", teammate_translation: "相等的", teammate_root: "equ", teammate_root_meaning: "相等", starred: false },
  { word: "equivalent", part_of_speech: "adj./n.", translation: "相等的; 等值的; 等價物", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "equ-i-val-ent", breakdown_meanings: "equ:相等|val:價值|ent:形容詞字尾", formula: "「價值」「相等」的", teammate_word: "value", teammate_translation: "價值", teammate_root: "val", teammate_root_meaning: "價值", starred: false },
  { word: "confidence", part_of_speech: "n.", translation: "信心; 自信; 信任", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "con-fid-ence", breakdown_meanings: "con:完全; 加強|fid:信任|ence:名詞字尾", formula: "「完全」地「信任」自己", teammate_word: "fidelity", teammate_translation: "忠誠", teammate_root: "fid", teammate_root_meaning: "信任", starred: false },
  { word: "fidelity", part_of_speech: "n.", translation: "忠誠; 忠實; 保真度", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "fid-elity", breakdown_meanings: "fid:信任; 信仰|elity:名詞字尾", formula: "堅定持守「信任」的特質", teammate_word: "confidence", teammate_translation: "信心", teammate_root: "fid", teammate_root_meaning: "信任", starred: false },
  { word: "reflect", part_of_speech: "v.", translation: "反射; 反映; 深思", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "re-flect", breakdown_meanings: "re:往回|flect:彎曲", formula: "光線或想法「折」「回」來", teammate_word: "flexible", teammate_translation: "易彎曲的", teammate_root: "flect", teammate_root_meaning: "彎曲", starred: false },
  { word: "flexible", part_of_speech: "adj.", translation: "易彎曲的; 靈活的; 彈性的", level: "Level 3-4 (學測)", category: "時空與狀態", breakdown: "flex-ible", breakdown_meanings: "flex:彎曲|ible:能...的", formula: "「能夠」「彎曲」的", teammate_word: "reflect", teammate_translation: "反射", teammate_root: "flex", teammate_root_meaning: "彎曲", starred: false },
  { word: "fluid", part_of_speech: "n./adj.", translation: "流體; 液體; 流動的; 不穩定的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "flu-id", breakdown_meanings: "flu:流|id:名詞/形容詞字尾", formula: "像液體般呈「流」動性質的", teammate_word: "fluent", teammate_translation: "流利的", teammate_root: "flu", teammate_root_meaning: "流", starred: false },
  { word: "fluent", part_of_speech: "adj.", translation: "流利的; 流暢的", level: "Level 3-4 (學測)", category: "感知與思考", breakdown: "flu-ent", breakdown_meanings: "flu:流|ent:形容詞字尾", formula: "言語如泉水般「流」出的", teammate_word: "fluid", teammate_translation: "流體", teammate_root: "flu", teammate_root_meaning: "流", starred: false },
  { word: "fortress", part_of_speech: "n.", translation: "要塞; 城堡", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "fort-ress", breakdown_meanings: "fort:強壯; 堅固|ress:名詞字尾 (地方)", formula: "非常「堅固」的防禦建築", teammate_word: "fortify", teammate_translation: "加強", teammate_root: "fort", teammate_root_meaning: "強壯", starred: false },
  { word: "fortify", part_of_speech: "v.", translation: "加強; 設防; 強化(體質)", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "fort-ify", breakdown_meanings: "fort:強壯|ify:動詞字尾 (使...化)", formula: "使力量變「強壯」", teammate_word: "fortress", teammate_translation: "要塞", teammate_root: "fort", teammate_root_meaning: "強壯", starred: false },
  { word: "effort", part_of_speech: "n.", translation: "努力; 盡力; 成果", level: "Level 3-4 (學測)", category: "動作與方向", breakdown: "ef-fort", breakdown_meanings: "ef:往外; 展現|fort:力量; 強壯", formula: "把身上的「力量」使「出」來", teammate_word: "fortress", teammate_translation: "要塞", teammate_root: "fort", teammate_root_meaning: "強壯", starred: false },
  { word: "diffuse", part_of_speech: "v./adj.", translation: "傳播; 擴散; 雜亂的", level: "Level 5-6 (分科)", category: "時空與狀態", breakdown: "dif-fuse", breakdown_meanings: "dif:分開; 散開|fuse:流; 灌", formula: "朝著不同方向「流」「散」", teammate_word: "confuse", teammate_translation: "使困惑", teammate_root: "fuse", teammate_root_meaning: "流", starred: false },
  { word: "infuse", part_of_speech: "v.", translation: "注入; 灌輸; 泡(茶)", level: "Level 5-6 (分科)", category: "動作與方向", breakdown: "in-fuse", breakdown_meanings: "in:往內|fuse:流; 灌", formula: "往「內部」「灌」入液體或思想", teammate_word: "confuse", teammate_translation: "使困惑", teammate_root: "fuse", teammate_root_meaning: "流", starred: false },
  { word: "influence", part_of_speech: "v./n.", translation: "影響; 感化", level: "Level 5-6 (分科)", category: "感知與思考", breakdown: "in-flu-ence", breakdown_meanings: "in:往內|flu:流|ence:名詞字尾", formula: "「流入」「內部」的力量 -> 影響", teammate_word: "fluent", teammate_translation: "流利的", teammate_root: "flu", teammate_root_meaning: "流", starred: false },
  { word: "evaluate", part_of_speech: "v.", translation: "評估; 評價", level: "Level 5-6 (分科)", category: "人與社會", breakdown: "e-valu-ate", breakdown_meanings: "e:往外|valu:價值|ate:動詞字尾", formula: "「評估」出「外在」的「價值」 -> 評估", teammate_word: "value", teammate_translation: "價值", teammate_root: "val", teammate_root_meaning: "價值", starred: false },
  { word: "valuable", part_of_speech: "adj./n.", translation: "有價值的; 貴重物品", level: "Level 3-4 (學測)", category: "人與社會", breakdown: "valu-able", breakdown_meanings: "valu:價值|able:可...的", formula: "「具有」「價值」的 -> 有價值的", teammate_word: "value", teammate_translation: "價值", teammate_root: "val", teammate_root_meaning: "價值", starred: false }
];

const EXTRA_GROUPS = [
  // Group A (201-300)
  "abandon|v.|放棄; 丟棄,ability|n.|能力; 才能,absolute|adj.|絕對的,absorb|v.|吸收,abstract|adj.|抽象的,abuse|v./n.|濫用; 虐待,academic|adj.|學術的,accent|n.|口音; 重音,access|n./v.|接近; 管道,accident|n.|意外; 事故,accompany|v.|陪伴,accomplish|v.|完成; 實現,according|adj.|根據的,account|n./v.|帳戶; 說明,accurate|adj.|精確的,accuse|v.|指控; 控告,achieve|v.|達成; 實現,acid|n./adj.|酸; 酸性的,acknowledge|v.|承認; 感謝,acquire|v.|獲得; 學得,adapt|v.|適應; 改編,adjust|v.|調整; 適應,admire|v.|欽佩; 讚賞,adopt|v.|採用; 收養,adore|v.|崇拜; 熱愛,advance|v./n.|前進; 進步,advantage|n.|優勢; 好處,adventure|n.|冒險; 奇遇,advertise|v.|做廣告,advise|v.|建議; 勸告,agency|n.|代理處; 機構,agenda|n.|議程,agent|n.|代理人; 媒介,aggressive|adj.|侵略性的; 有進取心的,agree|v.|同意,agriculture|n.|農業,alarm|n./v.|警報; 使驚恐,alcohol|n.|酒精,alert|adj./n./v.|警惕的; 警報,alliance|n.|聯盟; 同盟,allowance|n.|津貼; 零用錢,ally|n./v.|盟友; 結盟,alter|v.|改變; 修改,alternative|n./adj.|選擇; 替代的,amateur|n./adj.|業餘者; 業餘的,amaze|v.|使吃驚,ambition|n.|野心; 抱負,ambulance|n.|救護車,analysis|n.|分析,analyze|v.|分析,ancestor|n.|祖先,anchor|n./v.|錨; 主播; 錨定,ancient|adj.|古老的,anecdote|n.|評述; 軼事,anger|n./v.|憤怒; 使生氣,angle|n.|角度,anniversary|n.|週年紀念,announce|v.|宣佈,annoy|v.|打擾; 使煩惱,annual|adj.|年度的,anxiety|n.|焦慮; 渴望,anxious|adj.|焦慮的; 渴望的,apologize|v.|道歉,apology|n.|道歉,apparent|adj.|明顯的,appeal|v./n.|吸引; 呼籲,appetite|n.|食慾; 胃口,applaud|v.|鼓掌; 讚賞,applicant|n.|申請人,application|n.|應用; 申請,apply|v.|申請; 應用,appoint|v.|任命; 約定,appointment|n.|約會; 任命,appreciate|v.|感激; 欣賞,approach|v./n.|接近; 方法,approval|n.|同意; 批准,approve|v.|同意; 批准,approximate|adj.|大約的,architect|n.|建築師,architecture|n.|建築學,arena|n.|競技場; 舞台,argue|v.|爭論; 主張,argument|n.|爭論; 論點,arise|v.|升起; 產生,arouse|v.|喚醒; 激起,arrest|v./n.|逮捕,arrival|n.|到達,arrive|v.|到達,arrogant|adj.|傲慢的,arrow|n.|箭; 箭頭,article|n.|文章; 冠詞; 物品,artificial|adj.|人工的; 虛假的,artistic|adj.|藝術的,ascend|v.|上升; 攀登,ascent|n.|上升; 上坡,ashamed|adj.|羞愧的,aside|adv.|在旁邊,ask|v.|詢問; 要求,asleep|adj.|睡著的,asparagus|n.|蘆筍",
  // Group B (301-400)
  "aspect|n.|方面,aspire|v.|渴望,assemble|v.|集合; 裝配,assert|v.|聲稱,assess|v.|評估,assign|v.|分配; 指派,assist|v.|協助,associate|v.|聯想; 結交,assume|v.|假設; 承擔,assure|v.|向...保證,astonish|v.|使驚訝,athlete|n.|運動員,atmosphere|n.|大氣; 氣氛,attach|v.|附上; 貼上,attain|v.|達到; 獲得,attempt|v./n.|企圖; 嘗試,attend|v.|參加; 照顧,attitude|n.|態度,attract|v.|吸引,attribute|v./n.|歸因於; 特質,auction|n./v.|拍賣,audience|n.|聽眾; 觀眾,audio|adj./n.|聲音的; 音頻,audit|v./n.|審計; 旁聽,auditorium|n.|禮堂,author|n.|作者,authority|n.|權威; 當局,authorize|v.|授權,automatic|adj.|自動的,automobile|n.|汽車,autumn|n.|秋天,available|adj.|可得到的; 空閒的,avenue|n.|大道; 管道,average|n./adj.|平均的,avoid|v.|避免,awake|adj./v.|醒的; 喚醒,award|n./v.|獎品; 頒發,aware|adj.|意識到的,awesome|adj.|令人敬畏的; 極棒的,awful|adj.|極糟的,awkward|adj.|尷尬的; 笨拙的,bachelor|n.|學士; 單身漢,background|n.|背景,backward|adv./adj.|向後; 落後的,bacteria|n.|細菌,baggage|n.|行李,balance|n./v.|平衡,balloon|n.|氣球,barrier|n.|障礙; 柵欄,basic|adj.|基礎的,basin|n.|盆地; 水盆,battery|n.|電池,beauty|n.|美麗; 美人,behave|v.|表現; 舉止,behavior|n.|行為; 舉止,belief|n.|信念; 相信,belong|v.|屬於,beloved|adj./n.|心愛的; 愛人,beneficial|adj.|有益的,benefit|n./v.|利益; 有益於,betray|v.|背叛; 洩露,beverage|n.|飲料,bewilder|v.|使困惑,bias|n./v.|偏見,bibliography|n.|書目; 文獻,bicycle|n.|腳踏車,bid|v./n.|出價; 命令,bind|v.|捆綁; 約束,biography|n.|傳記,biology|n.|生物學,birth|n.|出生,bizarre|adj.|奇異的; 古怪的,blame|v./n.|責怪,blanket|n./v.|毯子; 覆蓋,bleed|v.|流血,blend|v./n.|混合,bless|v.|祝福,blind|adj./v.|盲的; 使失明,block|n./v.|街區; 阻擋,bloom|n./v.|開花,blossom|n./v.|開花,boast|v./n.|自誇,bold|adj.|大膽的,bomb|n./v.|炸彈; 轟炸,bond|n./v.|紐帶; 債券; 結合,border|n./v.|邊界; 接壤,boredom|n.|無聊; 厭煩,borrow|v.|借入,bother|v./n.|打擾; 實施,boundary|n.|邊界; 範圍,boycott|v./n.|聯合抵制,boyhood|n.|少年時期,boyish|adj.|孩子氣的,bracket|n.|括號,brag|v.|吹噓; 自誇,braid|n./v.|髮辮; 編織,brainstorm|n./v.|腦力激盪,brake|n./v.|煞車,brass|n.|黃銅,bravery|n.|勇敢",
  // Group C (401-500)
  "brace|n./v.|支架; 緊固,brain|n.|大腦; 智力,branch|n./v.|樹枝; 分支,brand|n./v.|品牌; 烙印,brave|adj.|勇敢的,breakdown|n.|故障; 崩潰,breathe|v.|呼吸,breed|v./n.|繁殖; 品種,breeze|n.|微風,brevity|n.|簡潔,brick|n.|磚塊,bridge|n./v.|橋; 架橋,brief|adj./v.|簡短的; 簡報,bright|adj.|明亮的; 聰明的,brilliant|adj.|輝煌的; 傑出的,broad|adj.|寬廣的,broadcast|v./n.|廣播,brochure|n.|小冊子,bronze|n./adj.|青銅; 青銅製的,bubble|n./v.|氣泡; 冒泡,budget|n./v.|預算,build|v.|建造,bulletin|n.|公告; 公報,bundle|n./v.|捆; 束,burden|n./v.|負擔,bureau|n.|局; 處,burst|v./n.|爆炸; 猛烈,bury|v.|埋葬; 掩埋,cabin|n.|小屋; 機艙,cabinet|n.|櫥櫃; 內閣,cable|n.|電纜; 電報,calamity|n.|災難,calculate|v.|計算,calendar|n.|日曆,campaign|n./v.|活動; 競選,campus|n.|校園,cancel|v.|取消,cancer|n.|癌症,candidate|n.|候選人,candle|n.|蠟燭,canvas|n.|帆布; 畫布,canyon|n.|峽谷,capacity|n.|容量; 能力,capital|n./adj.|首都; 資本; 大寫的,capsule|n.|膠囊; 艙,caption|n./v.|標題; 字幕,captive|n./adj.|俘虜; 被俘的,capture|v./n.|捕捉,carbon|n.|碳,career|n.|生涯; 職業,cargo|n.|貨物,carnival|n.|狂歡節; 嘉年華,carrier|n.|運送者; 載體,cart|n./v.|手推車; 運送,carve|v.|雕刻; 切開,case|n.|箱子; 案例; 情況,cash|n./v.|現金; 兌現,cassette|n.|卡帶,cast|v./n.|投擲; 演員陣容,castle|n.|城堡,casual|adj.|非正式的; 隨意的,catalog|n./v.|目錄; 登記,catastrophe|n.|大災難,category|n.|類別; 範疇,cater|v.|迎合; 提供餐飲,cathedral|n.|大教堂,caution|n./v.|小心; 警告,cautious|adj.|謹慎的,cave|n./v.|洞穴; 塌陷,cease|v./n.|停止,celebrate|v.|慶祝,celebrity|n.|名人,cell|n.|細胞; 單人牢房,cement|n./v.|水泥; 鞏固,cemetery|n.|墓地,censor|n./v.|審查員; 審查,census|n.|人口普查,center|n./v.|中心,central|adj.|中央的; 核心的,century|n.|世紀,ceremony|n.|儀式; 典禮,certificate|n./v.|證書; 證明,chain|n./v.|鏈條; 連鎖,chairman|n.|主席; 會長,challenge|n./v.|挑戰,chamber|n.|房間; 會議室,champion|n.|冠軍,chance|n.|機會; 可能性,change|v./n.|改變; 零錢,channel|n./v.|頻道; 管道,chaos|n.|混亂,chapel|n.|小教堂,chapter|n.|章節,character|n.|性格; 角色; 漢字,charge|v./n.|收費; 指控; 充電,charity|n.|慈善; 施捨,charm|n./v.|魅力; 迷人,chart|n./v.|圖表; 擺設,charter|n./v.|特許狀; 包租,chary|adj.|謹慎的",
  // Group D (501-600)
  "chase|v./n.|追逐,chat|v./n.|聊天,cheap|adj.|便宜的,cheat|v./n.|欺騙; 作弊,check|v./n.|檢查; 支票,cheer|v./n.|歡呼; 振奮,chemical|adj./n.|化學的; 化學製品,chemistry|n.|化學,cherish|v.|珍愛; 懷抱,chest|n.|胸膛; 箱子,chew|v.|咀嚼,chief|adj./n.|主要的; 首領,childhood|n.|童年,chill|n./v./adj.|寒冷; 冷卻,chimney|n.|煙囪,chip|n./v.|碎片; 晶片,choice|n.|選擇,choir|n.|唱詩班,choke|v.|窒息; 哽咽,choose|v.|選擇,chore|n.|雜務; 日常瑣事,chorus|n.|合唱團; 副歌,chronic|adj.|慢性的; 長期的,chronology|n.|年代學; 年表,circle|n./v.|圓圈; 環繞,circuit|n.|電路; 巡迴,circular|adj.|圓形的; 循環的,circulate|v.|循環; 流通,circumstance|n.|環境; 境況,cite|v.|引用; 傳喚,citizen|n.|公民; 市民,civil|adj.|公民的; 民事的,claim|v./n.|聲稱; 索賠,clarify|v.|澄清; 闡明,clash|v./n.|衝突; 撞擊聲,clasp|n./v.|扣環; 緊抱,classic|adj./n.|經典的,classify|v.|分類,clause|n.|條款; 子句,claw|n./v.|爪子; 抓,clay|n.|黏土,clean|adj./v.|乾淨的; 清潔,clear|adj./v.|清楚的; 澄清,clergy|n.|神職人員,clerk|n.|店員; 書記,clever|adj.|聰明的,client|n.|客戶; 顧客,cliff|n.|懸崖,climate|n.|氣候,climb|v./n.|攀登,cling|v.|緊貼; 依戀,clinic|n.|診所,clip|n./v.|夾子; 剪輯,clock|n.|鐘,clone|n./v.|複製; 克隆,close|v./adj.|關閉; 親密的,closet|n.|衣櫥,cloth|n.|布料,clothe|v.|給...穿衣,clothing|n.|衣服,cloud|n.|雲,clue|n.|線索,clumsy|adj.|笨拙的,cluster|n./v.|群; 聚集,coach|n./v.|教練; 馬車; 指導,coal|n.|煤炭,coalition|n.|聯合; 聯盟,coarse|adj.|粗糙的; 粗俗的,coast|n.|海岸,coat|n./v.|外套; 塗層,code|n./v.|密碼; 法規; 編碼,cognition|n.|認知,coherent|adj.|連貫的; 一致的,cohesion|n.|凝聚力,coin|n./v.|硬幣; 創造新詞,coincide|v.|同時發生; 相符,collapse|v./n.|倒塌; 崩潰,collar|n.|領子,colleague|n.|同事,collect|v.|收集,collection|n.|收集品,collective|adj.|集體的,college|n.|學院; 大學,collide|v.|碰撞; 衝突,collision|n.|碰撞; 衝突,colloquial|adj.|口語的,colony|n.|殖民地; 群體,column|n.|圓柱; 專欄,combat|n./v.|戰鬥; 對抗,combine|v.|結合,comedy|n.|喜劇,comfort|n./v.|舒適; 安慰,comic|adj./n.|滑稽的; 漫畫,command|v./n.|命令; 掌握,comma|n.|逗號,commander|n.|指揮官,commandment|n.|戒律,commando|n.|突擊隊員,commiserate|v.|憐憫; 同情,commissioner|n.|委員",
  // Group E (601-700)
  "commemorate|v.|紀念,commence|v.|開始,commend|v.|稱讚; 推薦,comment|n./v.|評論,commerce|n.|商業; 貿易,commercial|adj./n.|商業的; 廣告,commission|n./v.|佣金; 委員會; 委託,commit|v.|犯; 承諾,committee|n.|委員會,commodity|n.|商品,common|adj.|共同的; 常見的,commune|n./v.|公社; 親密交談,communicate|v.|溝通,commute|v./n.|通勤,compact|adj./v./n.|緊湊的; 協定,companion|n.|同伴,company|n.|公司; 陪伴,compare|v.|比較,compass|n.|指南針; 羅盤,compassion|n.|同情; 憐憫,compatible|adj.|相容的,compel|v.|強迫,compensate|v.|補償,compete|v.|競爭,competent|adj.|有能力的,competition|n.|競爭,competitive|adj.|競爭的,compile|v.|匯編; 編輯,complain|v.|抱怨,complaint|n.|抱怨; 投訴,complement|n./v.|補充物; 補足,complete|adj./v.|完整的; 完成,complex|adj./n.|複雜的; 綜合體,complexion|n.|膚色; 氣色,complicate|v.|使複雜,compliment|n./v.|恭維; 稱讚,comply|v.|遵守; 順從,component|n.|成分; 零件,compose|v.|組成; 作曲,composite|adj./n.|合成的; 合成物,composition|n.|作文; 作曲; 結構,compound|n./adj./v.|混合物; 複合的; 混合,comprehend|v.|理解,comprehensive|adj.|廣泛的; 綜合的,compress|v.|壓縮,compromise|n./v.|妥協; 讓步,compulsory|adj.|強制性的; 義務的,compute|v.|計算,computer|n.|電腦,comrade|n.|同志; 夥伴,conceal|v.|隱瞞; 隱蔽,concede|v.|讓步; 承認,conceit|n.|自滿; 自負,conceive|v.|構想; 懷孕,concentrate|v.|集中; 專注,concept|n.|概念,concern|v./n.|關心; 關係到,concert|n.|音樂會; 一致,concession|n.|讓步; 特許權,concise|adj.|簡潔的,conclude|v.|得出結論; 結束,conclusion|n.|結論,concrete|adj./n.|具體的; 混凝土,concur|v.|同意; 同時發生,condemn|v.|譴責; 判刑,condense|v.|濃縮; 凝結,condition|n./v.|條件; 狀態; 調理,conduct|n./v.|行為; 引導; 實施,conductor|n.|避雷針; 導體; 樂團指揮,cone|n.|圓錐體,confer|v.|商討; 授予,conference|n.|會議,confess|v.|承認; 供認,confession|n.|承認; 供認,confide|v.|吐露; 信賴,confidence|n.|信心,confident|adj.|有信心的,confine|v.|限制,confirm|v.|確認; 證實,conflict|n./v.|衝突,conform|v.|遵守; 符合,confront|v.|面臨; 對抗,confuse|v.|使困惑,confusion|n.|困惑; 混亂,congratulate|v.|祝賀,congratulation|n.|祝賀,congress|n.|國會; 大會,congruent|adj.|全等的,congruity|n.|一致,conjecture|n./v.|推測,conjoin|v.|結合,conjugal|adj.|婚姻的,conjugate|v.|變位,conjunctional|adj.|連接詞的,conjure|v.|變魔術; 召喚,conjurer|n.|魔術師,connective|adj./n.|連接的; 連接詞,connector|n.|連接器,connive|v.|默許; 縱容,connoisseur|n.|鑑定家; 行家",
  // Group F (701-800)
  "conjunction|n.|連接詞; 結合,connect|v.|連接,connection|n.|連接; 關係,conquer|v.|征服; 克服,conquest|n.|征服; 戰利品,conscience|n.|良心,conscious|adj.|有意識的,consecutive|adj.|連續的,consent|v./n.|同意,consequence|n.|後果; 影響,consequent|adj.|隨之發生的,conservation|n.|保存; 保護,conservative|adj./n.|保守的,conserve|v.|保存; 節約,consider|v.|考慮; 認為,considerable|adj.|相當大的,considerate|adj.|體貼的,consist|v.|由...組成; 在於,consistent|adj.|一致的; 連貫的,console|v./n.|慰問; 控制台,consolidate|v.|鞏固; 合併,consonant|n./adj.|子音; 一致的,conspicuous|adj.|顯眼的,conspire|v.|密謀; 陰謀,constant|adj./n.|恆定的; 常數,constituent|n./adj.|選民; 成分; 組成的,constitute|v.|構成; 制定,constitution|n.|憲法; 體質,constrain|v.|強迫; 限制,construct|v.|建造,consult|v.|諮詢; 查閱,consultant|n.|顧問,consume|v.|消耗; 消費,consumer|n.|消費者,consumption|n.|消耗; 消費,contact|n./v.|接觸; 聯繫,contain|v.|包含; 控制,container|n.|容器; 貨櫃,contaminate|v.|污染,contemplate|v.|沈思; 凝視,contemporary|adj./n.|當代的; 同時代的人,contempt|n.|輕視; 蔑視,contend|v.|競爭; 主張,content|n./adj./v.|內容; 滿足的,contest|n./v.|比賽; 爭奪,context|n.|上下文; 背景,continent|n.|大陸; 陸地,continual|adj.|頻繁的; 連續的,continue|v.|繼續,continuous|adj.|連續的; 不斷的,contract|n./v.|合約; 收縮,contradict|v.|反駁; 矛盾,contradiction|n.|矛盾; 反駁,contrary|adj./n.|相反的; 相反,contrast|n./v.|對比; 對照,contribute|v.|貢獻; 投稿,contribution|n.|貢獻; 投稿,control|v./n.|控制,controversial|adj.|有爭議的,controversy|n.|爭議; 論戰,convene|v.|召集; 集合,convenience|n.|便利; 方便,convenient|adj.|便利的; 方便的,convent|n.|女修道院,convention|n.|大會; 慣例,conventional|adj.|傳統的; 常規的,converge|v.|匯聚; 趨同,conversation|n.|對話; 交談,converse|v./n./adj.|交談; 相反的,convert|v.|轉變; 換算,convey|v.|傳達; 傳送,convict|v./n.|宣判有罪; 囚犯,conviction|n.|定罪; 確信,convince|v.|說服; 使確信,cooperate|v.|合作,cooperation|n.|合作,coordinate|v./n./adj.|協調; 座標,cope|v.|應付; 處理,copper|n.|銅,copyright|n.|著作權; 版權,cord|n.|細繩; 索,cordial|adj.|熱忱的,core|n.|核心,cork|n.|軟木塞,corkscrew|n.|開瓶器,cormorant|n.|鸕鶿,cornbread|n.|玉米麵包,cornea|n.|角膜,cornerstone|n.|奠基石,cornet|n.|短號,cornice|n.|簷口,cornucopia|n.|豐饒角,corny|adj.|陳腐的,corolla|n.|花冠,corollary|n.|推論,corona|n.|日冕,coronation|n.|加冕禮,coroner|n.|驗屍官,coronet|n.|小皇冠,corporal|adj./n.|肉體的; 下士",
  // Group G (801-900)
  "corn|n.|玉米; 穀物,corner|n./v.|角落; 逼入困境,corporation|n.|法人; 股份有限公司,corps|n.|兵團; 團體,corpse|n.|屍體,correct|adj./v.|正確的; 糾正,correction|n.|糾正; 修改,correlate|v./n.|相互關聯,correspond|v.|通信; 符合,correspondence|n.|通信; 符合,correspondent|n.|通訊員; 記者,corridor|n.|走廊,corrupt|adj./v.|腐敗的; 墮落,cosmetic|n./adj.|化妝品; 美容的,cosmic|adj.|宇宙的,cosmopolitan|adj./n.|世界性的; 世界主義者,cost|n./v.|花費; 成本,costume|n.|服裝; 戲裝,cottage|n.|小屋; 村舍,cotton|n.|棉花,couch|n.|沙發,council|n.|會議; 理事會,counsel|n./v.|法律顧問; 建議,counselor|n.|顧問; 輔導員,count|v./n.|計算; 伯爵,counter|n./v./adv.|櫃檯; 相反; 對抗,counteract|v.|抵消; 阻礙,counterfeit|adj./n./v.|偽造的; 贗品,counterpart|n.|相對應的人或物,countless|adj.|無數的,country|n.|國家; 鄉下,countryside|n.|農村; 鄉下,county|n.|縣; 郡,couple|n./v.|一對; 連結,courage|n.|勇氣,courageous|adj.|勇敢的,courier|n.|快遞員; 信差,course|n.|課程; 過程; 路線,court|n./v.|法庭; 球場; 奉承,courteous|adj.|有禮貌的,courtesy|n.|禮貌; 好意,cousin|n.|堂表兄弟姊妹,cover|v./n.|覆蓋; 封面,coverage|n.|新聞報導; 保險範圍,coward|n.|膽小鬼,coy|adj.|害羞的; 靦腆的,crack|v./n.|破裂; 裂縫,cradle|n./v.|搖籃; 撫育,craft|n.|工藝; 手藝; 船隻,cram|v.|填鴨式學習; 塞滿,crane|n./v.|起重機; 鶴; 伸長脖子,crash|v./n.|碰撞; 墜毀,crater|n.|火山口; 隕石坑,crave|v.|渴望,crawl|v./n.|爬行,crazy|adj.|瘋狂的,create|v.|創造,creation|n.|創造; 創立,creative|adj.|有創造力的,creature|n.|生物; 動物,credential|n.|憑證; 國書,credibility|n.|可信度; 信用,credible|adj.|可信的,credit|n./v.|信用; 學分; 相信,credulous|adj.|輕信的; 易受騙的,creed|n.|信條; 教義,creep|v.|爬行; 悄悄移動,crew|n.|全體工作人員,cricket|n.|蟋蟀; 板球,crime|n.|犯罪; 罪行,criminal|n./adj.|罪犯; 犯罪的,crisis|n.|危機,crisp|adj.|酥脆的,criterion|n.|標準; 準則,critic|n.|評論家; 批評者,critical|adj.|關鍵的; 批評的,criticism|n.|批評; 評論,criticize|v.|批評,crop|n./v.|農作物; 收割,cross|n./v./adj.|十字架; 越過; 生氣的,crouch|v./n.|蹲伏,crowd|n./v.|人群; 擁擠,crown|n./v.|皇冠; 加冕,crucial|adj.|關鍵性的; 至關重要的,crude|adj.|天然的; 粗糙的,cruel|adj.|殘酷的,cruelty|n.|殘酷; 虐待,cruet|n.|小瓶,crumb|n.|麵包屑,crumple|v.|弄皺,crunchy|adj.|鬆脆的,crusade|n.|十字軍,crusader|n.|改革運動者,crustacean|n.|甲殼綱動物,crusty|adj.|有脆皮的,crypt|n.|地下室,cryptic|adj.|神秘的,cryptography|n.|密碼學,crystalline|adj.|結晶的,crystallize|v.|結晶",
  // Group H (901-1000)
  "cruise|v./n.|巡航; 乘船遊覽,crumble|v.|崩潰; 碎裂,crunch|v./n.|咬碎聲; 關鍵時刻,crush|v./n.|壓碎; 迷戀,crust|n.|外殼; 麵包皮,cry|v./n.|哭; 喊叫,crystal|n./adj.|水晶; 水晶般的,cube|n.|立方體,cubic|adj.|立方的,cue|n./v.|提示; 暗示,culminate|v.|達到頂點,cultivate|v.|耕作; 培養,cultural|adj.|文化的,culture|n.|文化,cunning|adj./n.|狡猾的; 狡黠,cupboard|n.|碗櫥,curable|adj.|可治癒的,curator|n.|館長; 策展人,curb|n./v.|控制; 勒馬繩,cure|v./n.|治癒; 療法,curiosity|n.|好奇心,curious|adj.|好奇的,curl|v./n.|捲曲,currency|n.|貨幣; 流通,current|adj./n.|當前的; 洋流; 電流,curriculum|n.|課程; 全部課程,curse|n./v.|詛咒; 罵人,curtail|v.|縮減,curtailment|n.|縮減,cushion|n./v.|墊子; 緩衝,custody|n.|保管; 監護權,custom|n.|風俗; 習慣; 海關,customary|adj.|習慣的; 慣常的,customer|n.|顧客; 客戶,cut|v./n.|切; 割; 傷口,cute|adj.|可愛的,cycle|n./v.|循環; 週期; 騎車,cylinder|n.|圓柱體,cynical|adj.|憤世嫉俗的,cynicism|n.|憤世嫉俗,dairy|n./adj.|乳製品; 牛奶的,dam|n./v./adj.|水壩; 攔截,damage|n./v.|損害; 毀壞,damn|v./n./adj./adv.|運氣; 該死的,damp|adj./n./v.|潮濕的; 潮濕; 潮濕,dance|v./n.|舞蹈,danger|n.|危險,dangerous|adj.|危險的,dare|v./aux.|敢; 竟敢,dark|adj./n.|黑暗的; 黑暗,darkness|n.|黑暗,darling|n./adj.|親愛的,dash|v./n.|猛衝; 破折號,data|n.|數據; 資料,database|n.|資料庫,date|n./v.|日期; 約會,daughter|n.|女兒,dawn|n./v.|黎明; 破曉; 開始,day|n.|一天; 白天,daylight|n.|日光; 白晝,dazzle|v./n.|使眩目; 耀眼,dead|adj./adv./n.|死的; 完全地; 死者,deadline|n.|截止日期,deadly|adj./adv.|致命的; 極度地,deaf|adj.|聾的,deal|v./n.|交易; 處理,dealer|n.|商人; 交易商,dean|n.|院長; 主任,dear|adj./n./int.|親愛的; 昂貴的; 哎呀,death|n.|死亡,debate|n./v.|辯論; 爭論,debris|n.|碎片; 殘骸,debt|n.|債務; 借款,decade|n.|十年,decay|v./n.|腐爛; 衰退,deceive|v.|欺騙,decency|n.|得體; 體面,decent|adj.|得體的; 體面的,deception|n.|欺騙; 瞞騙,decide|v.|決定,decision|n.|決定,decisive|adj.|決定性的,deck|n.|甲板,declaim|v.|慷慨陳詞,declaration|n.|宣告,declare|v.|宣佈,decline|v./n.|下降; 婉拒,decode|v.|解碼,decompose|v.|分解,decorate|v.|裝飾,decoration|n.|裝飾,decorative|adj.|裝飾性的,decorum|n.|端莊; 禮貌,decrease|v./n.|減少,decree|n./v.|法令; 判決,dedicate|v.|奉獻,dedication|n.|奉獻,deduce|v.|推論,deduct|v.|扣除,deduction|n.|扣除; 推論"
];

